### ISSUE TITLE
Need enhancement/improvement in signIn and signUp page

### ISSUE THREAD

**Issue by AbhiDiva96** [VaibhavArora314/StyleShare#1]
## Needs improvement in frontend part of  singIn and signup page.

please assigned me under the gssoc'24
@VaibhavArora314 

## screenshot

![Screenshot 2024-05-27 182644](https://github.com/VaibhavArora314/StyleShare/assets/112077897/c463d81a-8ced-4482-acc5-b37c5d70574a)

![Screenshot 2024-05-27 182635](https://github.com/VaibhavArora314/StyleShare/assets/112077897/bdf27495-62c7-4d54-8b1f-a6dc63755fae)

## after improvement it would look like something this

![Screenshot 2024-05-26 081520](https://github.com/VaibhavArora314/StyleShare/assets/112077897/573765ef-71c1-4c0e-a4a2-6f9c4a197e5e)

**Comment by VaibhavArora314** [comment]
the screenshot you provided can have a little more width and padding as they are feeling clustered

**Comment by AbhiDiva96** [comment]
got it i will add more width and remove the remember option
@VaibhavArora314

**Comment by AbhiDiva96** [comment]
@VaibhavArora314.
I raised PR pls review it.
