### ISSUE TITLE
[Feature Request]: Adding Toast Notification to the whole webapp.

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

So, currently in this webapp their is a normal alert notification.
This issue will solve the alert notification to cool and visual appealing toast notification.

### Use Case

Better user experience.

### Benefits

Enhancing the overall app.

### Add ScreenShots

1. This is alert in current webapp.

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/99a9239e-9fd8-4f54-a192-949fe7776b10)

2. This is Toast notification which i gonna implementing.

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/db454494-cd8c-489a-a649-619e8f10e422)
 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@VaibhavArora314 Assign it to me :)

**Comment by VaibhavArora314** [comment]
Some toasts I can think of:
1. New post
2. Successful sign-in and sign-up
3. Account verified
4. OTP Sent
5. OTP Resent
6. Like & Dislike

If I missed any, feel free to add them.

**Comment by MeetDOD** [comment]
Ya sure >_<
