### ISSUE TITLE
[Feature Request]: Design About Us Page

### ISSUE THREAD

**Issue by BHS-Harish** [VaibhavArora314/StyleShare#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The site doesn't contain about us page. I'm interested to develop about us page.

### Use Case

New users may know more about our website through about us page.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
about us page already exists for the website and it is also added as a section in the website

**Comment by BHS-Harish** [comment]
Okay brother.
