### ISSUE TITLE
Ligh/Dark Mode

### ISSUE THREAD

**Issue by sharmi4590** [VaibhavArora314/StyleShare#115]
As users have different choices enabling a dark/light mode would enhance the user experience. 
I would like to work on this.

**Comment by VaibhavArora314** [comment]
@sharmi4590 any updates?

**Comment by manikumarreddyu** [comment]
/assign
can you please assign me this issue
i will work on it

**Comment by manikumarreddyu** [comment]
Hi ,@VaibhavAorai314 if this issue is not completed ,can you assign me under gssoc'24.

**Comment by VaibhavArora314** [comment]
create a hook that is imported in app.tsx, which manages the theme change logic and in the navbar, add an option to switch the theme.

**Comment by manikumarreddyu** [comment]
Sure @VaibhavArora314

**Comment by manikumarreddyu** [comment]
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/1aadd730-24f3-4991-b7dd-90fe518e8c24)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/77cdbdcb-755d-4272-9ba7-8f63f5f602c6)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/b812403e-039b-4076-b20e-94a803b7f761)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/c3b98fc5-3950-4d2f-826e-2e75f335008d)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/2667870f-8cf1-41c4-8051-f5ac432f8ff3)

**Comment by manikumarreddyu** [comment]
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/6183c222-9279-4141-8165-9e0639a2cc41)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/4daca22f-c08f-4067-9689-a34f909677e0)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/eb41ae51-36c1-4ff0-bf81-7fff314d6113)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/aff0d2a1-252a-48e0-b88e-944d6505bb52)

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check these once, half of the work is done
suggest me any changes

**Comment by manikumarreddyu** [comment]
after that i will make a PR

**Comment by VaibhavArora314** [comment]
> hey @VaibhavArora314 check these once, half of the work is done suggest me any changes

hey, I think the current website should be the same in dark mode and for the light mode you can use a color theme rather than plain white

**Comment by manikumarreddyu** [comment]
Sure @VaibhavArora314
