### ISSUE TITLE
[Feature Request]: Improving UI 

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

after clicking on read more..
it is showing like this
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/153be588-fc89-4bde-a246-c5fcc1b028db)
i want to improve the UI 

### Use Case

The page is not looking good 
adding beauty is fun and it improves the user interface more attarctive

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/c0a2744c-2514-4b99-9132-8a937701f9b8)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
can you provide some more information like what changes are you planning to improve this
