### ISSUE TITLE
[Bug]: After clicking on like button /unlike button the count is static 

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Making functionality for like button

### Expected behavior

the number incerements or decrements based on likes and dislikes

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/b8c1c0ff-09c6-45fc-b4b7-b0dcec30df73)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
It doesn't work on previous posts, when this feature is introduce after that the post which is created it will work fine and currenlty it is working perfectly.

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/339a7c26-72ab-421b-a3b9-8cf6118a55f9)

**Comment by manikumarreddyu** [comment]
excellent ...
