### ISSUE TITLE
[Feature Request]: Adding favourites label for the posts

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding favourites label for the post cards
after clicking on favourites icon it moves to the favourites page 
addition of new page named favourites is required

as of now i can do the frontend part
for backend it takes more time for me 

### Use Case

users Easily navigates to their favourite posts

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
This issue already exists #54 in pr #61

**Comment by manikumarreddyu** [comment]
okay..i got it
