### ISSUE TITLE
[Bug]: No Transition for the Hover effect

### ISSUE THREAD

**Issue by chaanakyaaM** [VaibhavArora314/StyleShare#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The buttons on the nav bar/header does not have the transition, so this makes the hover effect all of a sudden rather than smootly appearing.

### Expected behavior

The hover effects should be smooth.

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/131477601/700b5d67-0cf1-42d3-8c9e-752d22bc7cc6)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/b5962ab3-153b-4d89-85df-50593231e506)
