### ISSUE TITLE
[Feature Request]: Editable profile

### ISSUE THREAD

**Issue by anwesha2002** [VaibhavArora314/StyleShare#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Profile is not editable in current situation as a result if user wants to change the email address or username it is not possible as a result in order to change any mistake while signing up is not correctable 

### Use Case

In this way if user make any mistake while signing up in writing email or username , user can correct that in profile page. That will enhance the usability of project

### Benefits

In this way if user make any mistake while signing up in writing email or username , user can correct that in profile page. That will enhance the usability of project

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
@anwesha2002 any updates?

**Comment by anwesha2002** [comment]
@VaibhavArora314 I need prisma clients/DB authentication coz in localhost am not able to sign up or sign In. As I made the form for editable profile . I need authentication for integrating that

**Comment by anwesha2002** [comment]
@VaibhavArora314 can you provide it to me?

**Comment by VaibhavArora314** [comment]
https://github.com/VaibhavArora314/StyleShare?tab=readme-ov-file#setting-up-on-your-machine

@anwesha2002 read this, if still error persists share the error
