### ISSUE TITLE
[Feature Request]: UI of the footer

### ISSUE THREAD

**Issue by anwesha2002** [VaibhavArora314/StyleShare#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

UI of the footer is not looking good. 

### Use Case

I want to make the betterment of the UI of the footer . Now it looks not properly organised. 

### Benefits

It will make the footer look better that will match with the overall UI of the site.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
can you please provide more context about how it will be improved

**Comment by manikumarreddyu** [comment]
/assign

can you please assign me this 
after getting update from previous assignee
i will do it faster

**Comment by VaibhavArora314** [comment]
@anwesha2002 any updates?
