### ISSUE TITLE
[Feature Request]: Improve Navbar

### ISSUE THREAD

**Issue by harini-1597** [VaibhavArora314/StyleShare#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current navbar is good, but I'd like to make it look more professional. I'd like to add a better font for the StyleShare, add the created logo etc

### Use Case

The navbar would look better, more professional

### Add ScreenShots

![maxresdefault](https://github.com/VaibhavArora314/StyleShare/assets/128628820/d6b1292c-149e-4771-bfc4-52d293618812)

i'll make it look inspired by this, but I'll keep the gradient as it looks very cool.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
the navbar design looks good, just make sure it integrates well with the theme and does not conflicts with #124 or other navbar-related issues

**Comment by harini-1597** [comment]
hows this?
![Screenshot 2024-06-07 191154](https://github.com/VaibhavArora314/StyleShare/assets/128628820/036fb249-1053-46b7-b499-95a6c631767b)

**Comment by VaibhavArora314** [comment]
> hows this? ![Screenshot 2024-06-07 191154](https://private-user-images.githubusercontent.com/128628820/337673456-036fb249-1053-46b7-b499-95a6c631767b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjA2MzQsIm5iZiI6MTcxNzgyMDMzNCwicGF0aCI6Ii8xMjg2Mjg4MjAvMzM3NjczNDU2LTAzNmZiMjQ5LTEwNTMtNDZiNy1iNDk5LTk1YTZjNjMxNzY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNDE4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzgxZWIxNjE4NDJiZTAyZjgwZmY0MGJhMThmYzk2ODJmZDkzOWJmZGYyY2ZjNmEzYjdlZDg0MzE1MGE1YTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1K2y3kOlyPG52Kz-9kax6r4Z4DTsRahR8rOQj6GqQv4)

Don't use that icon in the navbar instead use the icon used as favicon, and the current navbar looks better with a gradient. this one is just looking too plain.

**Comment by harini-1597** [comment]
https://github.com/VaibhavArora314/StyleShare/assets/128628820/90188067-573d-4282-bdb8-a86ed063247a

what do you think?

**Comment by harini-1597** [comment]
https://github.com/VaibhavArora314/StyleShare/assets/128628820/307b074f-ad91-4d71-8863-09eee99e1139

lmk what you think

**Comment by VaibhavArora314** [comment]
> Recording.2024-06-08.151656.mp4 
> lmk what you think

looks good
