### ISSUE TITLE
[Bug]: Sign in , sign up text not visible.

### ISSUE THREAD

**Issue by nagalakshmi08** [VaibhavArora314/StyleShare#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The titles in sign in and sign up form is not visible. And also the hyperlinks to signin/signup is not aligned properly.

### Expected behavior

The title should be dark in order to be visible, and also the alignment of hyperlinks can be changed.

### Add ScreenShots

https://github.com/VaibhavArora314/StyleShare/assets/121669832/6084599e-5485-46ca-a083-647a03152625

Please assign me this issue, I would like to contribute to this project under GSSoC'24.

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
It is looking fine ?

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/e2ad2a48-3cfd-4b31-9895-397f3340cc71)

**Comment by VaibhavArora314** [comment]
The website is not loading properly on your local. Try clearing the cache or use a different browser or use incognito mode.
