### ISSUE TITLE
[Feature Request]: Leaderboard approach in style share

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I am thinking of the new features and this come in my mind, how about the leaderboard for the contributors who gives tailwind css componenets.

I will give top 3 user 1st,2nd,3rd title on the basis of the number of components they uploaded on the webapp.

The leaderboard will be visual appealing. so, its engage the user in competition result in more users to the webapp.

### Use Case

Engaging users. 

### Benefits

Ranks will be given example as 1st => Gold, 2nd => silver, 3rd => bronze and rest are given simple badges.

### Add ScreenShots

**Example:**

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/b6291635-6467-4b68-a2fc-82bf4247be84)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@VaibhavArora314 assign me this 😊

**Comment by VaibhavArora314** [comment]
Instead of the number of components, I am thinking of user reputation which is calculated as sum of (likes - dislikes) of every post.

**Comment by MeetDOD** [comment]
ok instead of components i will filter user by there like, assign it to me @VaibhavArora314
