### ISSUE TITLE
[Feature Request]: I want to add components under the Post section. I want to contribute under GSSOC'24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [VaibhavArora314/StyleShare#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add more components in the posts section to attract more and more users to this platform. I want to add card, breadcrumb and accordion components under posts section. 

### Use Case

This will add more compoents making the site more enriching for the users. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [x] I have starred the repository

**Comment by VaibhavArora314** [comment]
Can you please elaborate more on this

**Comment by ParnaRoyChowdhury777** [comment]
> Can you please elaborate more on this

Sir, 
I saw some template posts under the Post Page. I want to add some more components over there so that users can engage more as to they can get really helpful resources over this site. It will also be a showcase of good example of resources residing in the site.

**Comment by VaibhavArora314** [comment]
You can add more components through the website but they will not be considered as contribution in gssoc

**Comment by ParnaRoyChowdhury777** [comment]
> You can add more components through the website but they will not be considered as contribution in gssoc

Ok, Thanks for considering my reply.
