### ISSUE TITLE
scroll down progressbar

### ISSUE THREAD

**Issue by paulkrishanu4** [VaibhavArora314/StyleShare#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

scroll down progress bar enhances the UI of website

### Use Case

https://github.com/VaibhavArora314/StyleShare/assets/169196836/bb3d999d-35be-4f5c-8fd5-b60531b5caaa

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
so you want to implement the red progress bar on the top? but our website has a navbar so will it look good with it?

**Comment by paulkrishanu4** [comment]
colour will be according to the background of your website it will not be red

**Comment by manikumarreddyu** [comment]
Hi ,@VaibhavAorai314 if this issue is not completed ,can you assign me under gssoc'24.

**Comment by VaibhavArora314** [comment]
@paulkrishanu4 any updates?
