### ISSUE TITLE
enhance the footer  

### ISSUE THREAD

**Issue by jayanththalla** [VaibhavArora314/StyleShare#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the footer, the alignment and logo are not correct.
Adding more social media links to the footer

### Use Case

The footer looks dull and not proper alignment of the text 

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/121346142/24637176-35d3-4d41-9034-fcad6b3586ba)
![image](https://github.com/VaibhavArora314/StyleShare/assets/121346142/24637176-35d3-4d41-9034-fcad6b3586ba)

please assign me under gssoc @VaibhavArora314 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
#128
