### ISSUE TITLE
[Bug]: API Call Error When Creating a New Post

### ISSUE THREAD

**Issue by saurabhbakolia** [VaibhavArora314/StyleShare#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Create new post, The post is not creating, some API error is occuring. 
I would like to resolve that. 

### Expected behavior

When user click on the ```Submit``` button,  a new post should create. 

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/78996216/d5bc3566-0279-4845-b49c-9d5dfa260879)
![image](https://github.com/VaibhavArora314/StyleShare/assets/78996216/9ae3396d-9132-4155-9911-8a4851070179)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
it is working for me on live deployment. are you logged in and if yes then have you verified your account?
