### ISSUE TITLE
[Feature Request]: To add the contact form and contact page

### ISSUE THREAD

**Issue by ayush-848** [VaibhavArora314/StyleShare#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The contact page is missing.
I will add it and to it I will add a contact form

### Use Case

It will help the user to get connected.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by ayush-848** [comment]
@VaibhavArora314 Assign this issue to me. I will complete it within a day or two

**Comment by VaibhavArora314** [comment]
This issue already exists #73
