### ISSUE TITLE
[Feature Request]: Muti Language support 

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature enable user to switch between different languages, currently i am focusing to convert english to hindi but i will implement more languages as you suggest.

### Use Case

Any user can interact with the webapp without languagae barriers

### Benefits

Increase User Experience. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
how are you planning to implement this feature?

**Comment by MeetDOD** [comment]
There is a npm package called i18 and i18-next, with this the languagae of the webapp can be change, so i will implement this feature on the static text and all not on post because the post contain the english words and code that cannot be change. on home page, about us heading like posts, leaderboard and all.

**Comment by VaibhavArora314** [comment]
I have no idea how that works so I am not currently assigning any badge and will assign it after reviewing pr.

**Comment by MeetDOD** [comment]
Ok got it
