### ISSUE TITLE
add logo in the navbar

### ISSUE THREAD

**Issue by jayanththalla** [VaibhavArora314/StyleShare#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding the logo in the  navbar 

### Use Case

All website have the logo in the navbar in this website the  logo is missing

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/121346142/8a7fc8a0-9c5c-43e4-9746-c8b44a0d00d3)
please assign me @pa
please label under the gssoc 
### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Part of #130
