### ISSUE TITLE
[Feature Request]: If the user does a wrong search in the search bar

### ISSUE THREAD

**Issue by SrinivasDevolper** [VaibhavArora314/StyleShare#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

If the user does a wrong search in the search bar then needs to show the text **No Results Found**it 

**I am GSSOC24 contributor
Please assign me, I would like to work on it**

### Use Case

Better understanding on search bar

### Benefits

Better understanding on search bar

### Add ScreenShots

![no-result text](https://github.com/VaibhavArora314/StyleShare/assets/121508628/bbaba9ac-f9ef-4f80-8066-ced339235338)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
@SrinivasDevolper any updates?
