### ISSUE TITLE
[Feature Request]: Enhancing "Recent Posts Added" Section

### ISSUE THREAD

**Issue by asthanegi14** [VaibhavArora314/StyleShare#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to update the "Recent Posts Added" Section.
From this:-

![Screenshot (992)](https://github.com/VaibhavArora314/StyleShare/assets/93486108/f4f1b1be-6804-4fb2-bb3a-558163dbc466)

To something like this:-

![ss](https://github.com/VaibhavArora314/StyleShare/assets/93486108/575fe78a-3a3f-4376-9d68-255e2dbbca71)

### Use Case

It will increase user interactivity and make the website more impressive.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
the screenshot you provided looks more like the testimonials section than the posts section. secondly, we don't have images of our users.
