### ISSUE TITLE
[Bug]: Footer Links for Privacy Policy and Terms and Conditions Leading to Blank Page

### ISSUE THREAD

**Issue by Satuti99** [VaibhavArora314/StyleShare#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In  footer when we click on Privacy Policy,
Terms and Conditions its leading to blank page.

### Expected behavior

Whenever click on Privacy Policy it should redirect to a page displaying the website's Privacy Policy, detailing how user data is collected, used, and protected.

Whenever click on Terms and Conditions it should redirect to a page displaying the website's Terms and Conditions, outlining the rules and guidelines for using the website.

### Add ScreenShots

https://github.com/VaibhavArora314/StyleShare/assets/115169702/1d758ef6-9bba-42db-8090-bc467156ac7b

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
make a single page where sections exist for each of these links
