### ISSUE TITLE
Add hover effect to footer links

### ISSUE THREAD

**Issue by root-0101** [VaibhavArora314/StyleShare#160]
It would be great if we add a hover effect to the footer links which the webpage engaging 

![Screenshot 2024-06-10 150958](https://github.com/VaibhavArora314/StyleShare/assets/142779809/b6b7afb5-9531-4a5c-8c1a-3d3955699437)

**Comment by anshikatiwari20** [comment]
**Description:**
Currently, the footer links do not have a hover effect, which can enhance user interaction and provide visual feedback when users hover over the links. I would like to implement a subtle hover effect that changes the text color of the links when hovered over, improving the overall user experience of the website.

**Screenshot:**
![Screenshot 2024-06-19 022632](https://github.com/VaibhavArora314/StyleShare/assets/143124119/72db8583-830d-4bd1-ae97-175f1d5c7c0e)

@VaibhavArora314 I am a GSSoC contributor and would like to work on adding a hover effect to footer links as described in issue #160. Could you please reassign this issue to me? Thank you!
