### ISSUE TITLE
[Documentation Update]: update screenshot and add video in readme

### ISSUE THREAD

**Issue by root-0101** [VaibhavArora314/StyleShare#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

We need to update the screenshot in the readme file with the current UI of the website

### Suggested Change

We need to update the screenshots in readme

### Rationale

As it is important for the visitors/contributors to have a idea of the updated webpage and also it's important to make sure that the documentation is updated regularly 

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
also, add a full working demo video of website

**Comment by root-0101** [comment]
https://github.com/VaibhavArora314/StyleShare/assets/142779809/d201365e-974e-42a2-86ed-05ae692a8747

**Comment by root-0101** [comment]
https://github.com/VaibhavArora314/StyleShare/assets/142779809/d033eddd-2dd8-4180-92ba-73413175fe62

**Comment by VaibhavArora314** [comment]
The video is still not showing.

**Comment by VaibhavArora314** [comment]
Nvm it took some time to load the video
