### ISSUE TITLE
[Feature Request]: Add upload file 

### ISSUE THREAD

**Issue by root-0101** [VaibhavArora314/StyleShare#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It would be great if we add an upload file button to upload code snippet directly. so, user can easily upload the code file.

### Use Case

It provides user to seamlessly upload their code 

### Benefits

It helps user to have an easier way to upload their code 

### Add ScreenShots

![Screenshot 2024-06-10 153036](https://github.com/VaibhavArora314/StyleShare/assets/142779809/d524aee8-319c-4ddc-a246-e5aea7c2c553)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
The problem with uploading the file is that we will have to do a separate handling for its preview by extracting content
