### ISSUE TITLE
Add annotation 

### ISSUE THREAD

**Issue by root-0101** [VaibhavArora314/StyleShare#163]
It would be great if we add the annotation to the like, dislike and favorite buttons on hovering like most modern websites have.

![Screenshot 2024-06-10 154235](https://github.com/VaibhavArora314/StyleShare/assets/142779809/6681563d-bb13-44a1-8c7b-9482bf77c6de)

**Comment by VaibhavArora314** [comment]
@root-0101 any updates?

**Comment by anshikatiwari20** [comment]
**Description:**
The task involves adding annotations to the project to improve code readability and maintainability. 

@VaibhavArora314 I am a GSSoC contributor and would like to work on adding annotations as described in issue #163. Could you please assign this issue to me? Thank you!

**Comment by VaibhavArora314** [comment]
The functionality of like and dislike has been changed very much but go ahead
