### ISSUE TITLE
Show Hover effects on footer's Github and Home icons.

### ISSUE THREAD

**Issue by zalabhavy** [VaibhavArora314/StyleShare#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

There are no hover effects on footer's github and home icons.

![image](https://github.com/VaibhavArora314/StyleShare/assets/126322584/264e9639-74c2-4d8d-bc7d-2a2b7e922988)

### Suggested Change

I will add hover effects that will give better looks.

### Rationale

I will add CSS some scale to look good.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
#160

**Comment by VaibhavArora314** [comment]
Since these are not implemented in #160, go ahead.
