### ISSUE TITLE
Navbar ui

### ISSUE THREAD

**Issue by naisargi17** [VaibhavArora314/StyleShare#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The ui of Navbar is not matching with whole website, especially the gradient colour button . We can make it more professional.

### Use Case

The first look goes to navbar ,so it should me more attractive and user-friendly. The user should feels reliable according to color theory.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
can you please provide more context to which colors are you planning to use and if possible a demo would be great

**Comment by naisargi17** [comment]
Kindly check this out.
![image](https://github.com/VaibhavArora314/StyleShare/assets/111778403/c47f0ece-7180-4649-b5a7-e4a67c80ab11)

**Comment by naisargi17** [comment]
https://github.com/VaibhavArora314/StyleShare/assets/111778403/6c9aaeb3-5ab7-4207-b6d7-eef27188bf7c

**Comment by manikumarreddyu** [comment]
hi @naisargi17  can you see this once..i think what you have changed is good better than previous one
but i am sorry to say this..that..colour is not complyig with the remaining portion.

so i made some little changes..

Please let me know if you like this and if any minor change you want , we can discuss it also. Feel free to say it .
https://style-share-c45in581e-vaibhavs-projects-0c395dc9.vercel.app/app/

**Comment by VaibhavArora314** [comment]
> Please let me know if you like this and if any minor change you want , we can discuss it also. Feel free to say it . https://github.com/VaibhavArora314/StyleShare/assets/111778403/6c9aaeb3-5ab7-4207-b6d7-eef27188bf7c

raise a pr. I will suggest the changes there. Also, use another color that contrasts well with the website theme.

**Comment by manikumarreddyu** [comment]
Hi ,@VaibhavAorai314 if this issue is not completed ,can you assign me under gssoc'24.
