### ISSUE TITLE
[Bug]: Responsive issue on home-page when width is below 400px

### ISSUE THREAD

**Issue by upsaurav12** [VaibhavArora314/StyleShare#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the homepage home page is not responsive like there is some extra width when the width size is below ``400px`` 

### Expected behavior

It should be responsive below 400px and should not have extra width

### Add ScreenShots

Instead of ScreenShots i am adding video where you can easily see the issue 

https://github.com/VaibhavArora314/StyleShare/assets/116784047/5d657b76-3ee9-4142-8b7c-bc6c473d8f72

### On which device are you experiencing this bug?

Linux

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
This is probably due to "Welcome to Style Share" text causing an x-overflow

**Comment by VaibhavArora314** [comment]
I think this has been resolved
