### ISSUE TITLE
[Feature Request]: Improve Navbar in smaller Screen Size

### ISSUE THREAD

**Issue by upsaurav12** [VaibhavArora314/StyleShare#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When the user is not ``sign-in`` and we see the navbar in smaller screen size we can see that the ``sign-in`` and ``sign-out`` button is not looking good.
![image](https://github.com/VaibhavArora314/StyleShare/assets/116784047/17f062c8-fa11-4690-ba7f-3f1d9b397902)
We can improve this by putting the ``buttons`` in the same level by using `display:flex``

### Use Case

This is for ``user-experience`` because when the user see  ``navbar`` for the first time then this would not be good ``ux``

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@VaibhavArora314

**Comment by upsaurav12** [comment]
i am working on this issue just trying to setup the project in local system

**Comment by TheNikhilRaj** [comment]
> i am working on this issue just trying to setup the project in local system

okay no problem is there any problem in setup local?
@upsaurav12

**Comment by upsaurav12** [comment]
yes i am having problem while setup especially in ``.env``

**Comment by VaibhavArora314** [comment]
I think this has been resolved, if not feel free to reopen this
