### ISSUE TITLE
[Feature Request]: Inbuilt css complier in style share

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Integrating a Tailwind CSS compiler within your application where users can write code on the left side and see the output on the right side can greatly enhance the user experience.

### Use Case

User experience.

### Benefits

Scaling the webapp

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/5c62c884-ae77-4a54-99e7-4f9aa337e56f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@VaibhavArora314 Hey, the work is done just assign me this under gssoc :)

**Comment by VaibhavArora314** [comment]
how are you planning to implement this? also, this feature can work well like we can give an option in this compiler to publish the component which will redirect to /new-page and have code snippet already in the form.

**Comment by MeetDOD** [comment]
@VaibhavArora314 can you explain me in depth the approach ?

**Comment by MeetDOD** [comment]
@VaibhavArora314 i implemented the approach as you told me see the pr #189

**Comment by VaibhavArora314** [comment]
Sorry for the late response, I will review the pr and see if any changes are needed.

**Comment by MeetDOD** [comment]
> Sorry for the late response, I will review the pr and see if any changes are needed.

No Prob @VaibhavArora314 , take your time .
