### ISSUE TITLE
[Documentation Update]: Add PR_TEMPLATE.md

### ISSUE THREAD

**Issue by codercake** [VaibhavArora314/StyleShare#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

It’s essential to provide a detailed explanation of how this feature works and its implementation.

### Suggested Change

This should include:
1. A step-by-step guide on how the feature operates.
2. Code snippets illustrating the implementation.
3. Security considerations and best practices.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
there already exists a pr template in the repo
