### ISSUE TITLE
[Feature Request]: Add "Continue with Google" Feature

### ISSUE THREAD

**Issue by Saksham2k3s** [VaibhavArora314/StyleShare#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To enhance user convenience and streamline the registration and login processes, we propose adding a "Continue with Google" feature. This will allow users to sign up and log in using their Google accounts, offering a quicker and more seamless experience.

### Use Case

Adding a "Continue with Google" feature would simplify the registration and login processes for users. It will provide a faster and more convenient way for users to access the application without having to remember additional login credentials.

### Benefits

Implementing this feature would:

- Increase user sign-ups and retention by providing a seamless login experience.
- Reduce the barrier to entry for new users.
- Enhance user satisfaction and convenience.
- Leverage the security and reliability of Google’s authentication system.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
A issue already exists for Google authentication
