### ISSUE TITLE
[Feature Request]:  Preview mode while creating a new post or updating a current one

### ISSUE THREAD

**Issue by Parth18Shah** [VaibhavArora314/StyleShare#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This will allow the user to confirm whether their code is working when adding a new post or updating an existing one.
It aims to achieve something similar to #171 but keeps it static instead of a dynamic compiler (using the current preview method), which can be enhanced and added later.

### Use Case

Helps the user verify their code before adding/ updating it.

### Benefits

As mentioned above in the user case section.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Assigning it level2 since most of the functionality was already built and simply needed to be integrated in these components.
