### ISSUE TITLE
[Feature Request]: To see other user profile and their posts.

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When user click this they will redirect to that user profile page where he/she can see the all info regarding that user and all the post created by him/her.

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/ae2aa606-7383-48b3-a916-a1fe58a1824b)

### Use Case

Public

### Benefits

User enhancement

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Create a route for profile/userid which is similar to the current user profile. Just that it does not shows that user's email.

**Comment by MeetDOD** [comment]
Okay, so i will hide the email and rest should be public right ?

**Comment by VaibhavArora314** [comment]
> Okay, so i will hide the email and rest should be public right ?

Yes
