### ISSUE TITLE
[Feature Request]: Adding Testimonials

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding reviews or testimonilas will enhance the user experience and they would get to know about others experience as well. It increases the user's trust.

### Use Case

Enhance the user experience and they would get to know about others experience

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
add a moving carousel with 4-5 dummy testimonials

**Comment by manikumarreddyu** [comment]
sure @VaibhavArora314
