### ISSUE TITLE
[Feature Request]: search bar for leaderboard

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As the number of users increases in future...it will become hard to find his position in leader board
adding search bar for leaderboard table resolves this problem

### Use Case

Search bar makes easy to find ranking of anyone in leaderboard

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
I don't think it's necessary because by default only top 10 users are displayed on the board. so, no need for searching .

**Comment by manikumarreddyu** [comment]
okay..@MeetDOD
