### ISSUE TITLE
[Feature Request]: Edit button on profile section. 

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Edit feature is fine, but it show when a user go inside the post by clicking on the read more button.
I want to add edit button near the delete button so that user will have a full control over his/her profile.

### Use Case

User enhancement 

### Benefits

user engagement

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/7754614a-93a6-4be6-8966-e29fc97a48a4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
A similar issue exists #127. In case she is inactive then I will assign it to you.

**Comment by VaibhavArora314** [comment]
Assigning it level1 since only an icon needed to be added which navigates with the state

**Comment by MeetDOD** [comment]
> Assigning it level1 since only an icon needed to be added which navigates with the state

😄 okay

**Comment by MeetDOD** [comment]
@VaibhavArora314 the person who had created the edit post had not created any routes /edit he/she is calling a component instead without navigation. so, should i create a separate route ?

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 the person who had created the edit post had not created any routes /edit he/she is calling a component instead without navigation. so, should i create a separate route ?

sure but it will be a lot of headache separating the component without breaking anything

**Comment by MeetDOD** [comment]
Yah but i don't have another choice :(
