### ISSUE TITLE
Enhance README.md

### ISSUE THREAD

**Issue by VaibhavArora314** [VaibhavArora314/StyleShare#2]

**Comment by its-kumar-yash** [comment]
Hey @VaibhavArora314, please give some context that what enhancement you required in readme.

**Comment by VaibhavArora314** [comment]
> Hey @VaibhavArora314, please give some context that what enhancement you required in readme.

I want sections such as Project Description, Screenshots, Contributors, How to Contribute, License (simply link the license file in the repo) and so on.

![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/b891626c-94f6-4555-8b32-cd67fece8d20)

**Comment by its-kumar-yash** [comment]
Understood. I want to work on this. Kindly assign this to me
