### ISSUE TITLE
[Feature Request]: Adding copy , download buttons in code editor

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding copy , download buttons in code editor

### Use Case

It makes easier for user to download his code 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
The download feature will be worked upon in another issue after css, js options will be integrated with the htm code snippet 
As for the copy, you can add a copy icon

**Comment by manikumarreddyu** [comment]
okay

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 check it once , and let me know any changes required.
Thank you!!
