### ISSUE TITLE
[Feature Request]: Adding  new sections in home page

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

section 1- Quick Video Tour: Adding a short video (30-60 seconds) showcasing how to use the platform.
section 2 - Frequently Asked Questions (FAQ)
section 3-  SHowcasing about our code editor

In footer

section 3-  Social Media Links in footer

Adding  icons linking to social media profiles (Facebook, Twitter, LinkedIn, Instagram).

### Use Case

providing quick video tour helps users to know bout the platform

providing FAQs are very useful

adding social media links helps very much in expanding project

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Only add faqs and showcasing the code editor section
No need to add a video in the websites 
For the social icons, there is no need to add more since we don't have links for them

**Comment by manikumarreddyu** [comment]
sure.. @VaibhavArora314
