### ISSUE TITLE
[Feature Request]: Building ChatBot with React-Chatbot-Kit

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Building ChatBot with React-Chatbot-Kit

chatbot helps for the users in many ways

### Use Case

chatbot helps for the users in many ways

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
I don't think this feature is needed much in the website

**Comment by manikumarreddyu** [comment]
okay
