### ISSUE TITLE
[Feature Request]: Adding Cheatsheet page for tailwind css with search bar

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding Cheatsheet page for tailwind css with search bar

### Use Case

It helps users in designing faster

### Add ScreenShots

<img width="613" alt="image" src="https://github.com/VaibhavArora314/StyleShare/assets/133508962/b252a5dc-f635-4349-803f-9e452ec17e24">

<img width="950" alt="image" src="https://github.com/VaibhavArora314/StyleShare/assets/133508962/be5813d1-9df2-49a6-8221-162caac48aa0">

like thse for all components avialable in tailwind css

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
I don't think this is needed in our website

**Comment by manikumarreddyu** [comment]
okay
