### ISSUE TITLE
[Feature Request]: code editor is missing

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

code editor is missing

### Use Case

code editor is very important

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/404a5345-bdf9-435b-beba-efb8b9699d0e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@manikumarreddyu ya bro i don't who removed it 🤔

**Comment by manikumarreddyu** [comment]
@naisargi17 after her PR is merged it is gone

**Comment by MeetDOD** [comment]
I see

**Comment by manikumarreddyu** [comment]
PR #207
