### ISSUE TITLE
[Feature Request]: Add Social Media Links to User Profile Section

### ISSUE THREAD

**Issue by Saksham2k3s** [VaibhavArora314/StyleShare#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to enhance the user profile section by adding social media links. This will allow users to display their social media profiles, making it easier for others to connect with them on various platforms.

### Use Case

A visitor wants to view another user's social media profiles to connect with them on various platforms.

### Benefits

A visitor wants to view another user's social media profiles to connect with them on various platforms.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
which social media links are you planning to add?

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@VaibhavArora314 
i can add this instagram, linkedin, twitter, etc.
@VaibhavArora314 you told some suggestions i can add it.

**Comment by Saksham2k3s** [comment]
Hi @VaibhavArora314 ,
I'm planning to add user social media links so that other users can reach out to them.

**Comment by VaibhavArora314** [comment]
> I would like to work on this issue , please assign this to me. @VaibhavArora314 i can add this instagram, linkedin, twitter, etc. @VaibhavArora314 you told some suggestions i can add it.

I think you should allow users to add GitHub, LinkedIn, and twitter URL options.
these options need to be provided on user's profile page and not while signing up

**Comment by UtkarshBirla28** [comment]
@VaibhavArora314 Assign it to me sir i will resolve it ASAP

**Comment by VaibhavArora314** [comment]
@TheNikhilRaj any updates?

**Comment by TheNikhilRaj** [comment]
@VaibhavArora314  Yes i'm still working on it!!

**Comment by UtkarshBirla28** [comment]
@VaibhavArora314 Assign me

**Comment by TheNikhilRaj** [comment]
@UtkarshBirla28 I'm working on this.

**Comment by MeetDOD** [comment]
@VaibhavArora314 assign me I will complete it within a hour, if anyone is working on it that's fine, but I think it's been a long time and this is just a simple feature It should be completed earlier !

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 assign me I will complete it within a hour, if anyone is working on it that's fine, but I think it's been a long time and this is just a simple feature It should be completed earlier !

Sure, go ahead
