### ISSUE TITLE
[Feature Request]:  Navbar again changed to previous version after someones PR is merged

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Navbar again changed to previous version after someones PR is merged

### Use Case

Navbar again changed to previous version after someones PR is merged

### Add ScreenShots

previous
<img width="938" alt="image" src="https://github.com/VaibhavArora314/StyleShare/assets/133508962/b4b485bb-6a56-47c8-b01d-5c5c9b186a88">

new version

<img width="932" alt="image" src="https://github.com/VaibhavArora314/StyleShare/assets/133508962/07f50ae4-6dd9-4df1-895d-a00c745c4c2f">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
i may have missed this while merging a pr, just find what changes were done and undo them

**Comment by manikumarreddyu** [comment]
okay
