### ISSUE TITLE
[Documentation Update]: Updating readme file

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

many changes made in website

### Suggested Change

changes needed in readme

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
please specify the changes also, this is very ambigous

**Comment by manikumarreddyu** [comment]
As we have made many changes
1. Screen shots should be replaced with new ones
2. For setting up backend..clearly stating how to run
  Especially for prisma...many are confusing
3.Adding youtube link for generating 16 digit app password 
4.adding views,forks,stars,issues,pulls in the form of badges in the top of readme file
