### ISSUE TITLE
[Feature Request]: Display Number of Likes and Dislikes on Post Card

### ISSUE THREAD

**Issue by Saksham2k3s** [VaibhavArora314/StyleShare#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, the post card does not show the number of likes or dislikes each post has received. To enhance user engagement and provide feedback on post popularity and sentiment, we should display the number of likes and dislikes on each post card.

### Use Case

The viewer can view the number of likes and dislikes on the post card as well

### Benefits

The viewer can view the number of likes and dislikes on the post card as well

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
actually, I am planning this to be integrated with the reaction functionality
