### ISSUE TITLE
[Bug]: Logout Text on Header Becomes Harder to See on Hover

### ISSUE THREAD

**Issue by Saksham2k3s** [VaibhavArora314/StyleShare#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When hovering over the "Logout" text on the header, it becomes harder to see due to the color change. This issue affects user experience as it makes the logout option less visible and harder to identify.

### Expected behavior

The "Logout" text should remain clearly visible and readable when hovered over.

### Add ScreenShots

![logout harder](https://github.com/VaibhavArora314/StyleShare/assets/129402285/ec9b600b-b9f4-4901-9866-0d2024352989)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
make ita button like signin and signup button

**Comment by VaibhavArora314** [comment]
I think this has been resolved, if it still exists feel free to reopen this
