### ISSUE TITLE
[Feature Request]: Addition of download button before copy option in Code editor

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

recently 

the problem you have mentioned like this:

The download feature will be worked upon in another issue after css, js options will be integrated with the html code snippet
As for the copy, you can add a copy icon

it is solved
so i can proceed

### Use Case

download option will be very useful for the users

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
actually, there is a pending issue of downloading as zip #196 
when this is implemented, it can be integrated with the code editor as well
