### ISSUE TITLE
[Feature Request]: Remove button in favourite page for posts

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

it enables the users to remove posts from favourites

### Use Case

it enables the users to remove posts from favourites

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
@VaibhavArora314 assign to @MeetDOD

**Comment by vaibhavi-singh-673** [comment]
@VaibhavArora314 can you assign it to me if it has not been finished

**Comment by MeetDOD** [comment]
@vaibhavi-singh-673 currently I am doing it !

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 can you assign it to me if it has not been finished

you can comment on any other unassigned issue or raise a new issue
