### ISSUE TITLE
[Feature Request]: Open for file option in code editor

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Open existing code files stored locally on device into code editor

### Use Case

it is very useful for the users to open files directly from our website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
so the user will be able to upload the code file which is loaded into the code editor?

**Comment by manikumarreddyu** [comment]
From his device i.e.local storage to code editor

**Comment by VaibhavArora314** [comment]
user can just copy paste his code because this will be too much headache to upload the file then parse it since js code option is also about to be integrated in the pr
