### ISSUE TITLE
[Feature Request]: Social Sharing:  allow users to easily share your posts on social media platforms.

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Social Sharing: Integrate social sharing buttons to allow users to easily share your posts on social media platforms.

### Use Case

it will be very useful

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
this is already implemented, please check before raising

**Comment by manikumarreddyu** [comment]
> this is already implemented, please check before raising

Directly from code editor 
I forget to mention code editor @VaibhavArora314
