### ISSUE TITLE
[Feature Request]: Setting unique id for each and every post 

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 Setting unique id for each and every post

### Use Case

this is very helpful..so that if we can remove contentless post very easily

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
posts do have an id. what do u mean?

**Comment by manikumarreddyu** [comment]
> posts do have an id. what do u mean?

Okay..displaying I'd number for post card....if there any unuseful  post the admin can remove it whenever users report
