### ISSUE TITLE
[Feature Request]: Real-time error checking in code editor

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

implementing real-time error checking , 
as users type their code to help them identify and fix bugs more quickly.

### Use Case

users fix bugs more quickly in code editor

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
how are you planning to implement this? this can increase the website bundle size heavily

**Comment by manikumarreddyu** [comment]
I just got the feature idea...I didn't know about bundle size..
If there is anyone who can do this without increasing bundle size you can assign to them..no worries
I think the idea is great ...put it like help wanted label

**Comment by VaibhavArora314** [comment]
> I just got the feature idea...I didn't know about bundle size.. If there is anyone who can do this without increasing bundle size you can assign to them..no worries I think the idea is great ...put it like help wanted label

if you have any approach feel free to explain here. the only thing I am worried about real-time error checking can be heavy on client side and make it slow if not properly handled
