### ISSUE TITLE
[Feature Request]: Save as option in code editor

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

for saving the file to a specific location in user device

### Use Case

it is very helpful for saving files to local device

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
giving download option is same as save as option since when downloading a window opens up for save location
your own issues are conflicting themselves. please see before raising issues
