### ISSUE TITLE
[Bug]: Privacy policy ,cookie policy and terms and condition are given on same page

### ISSUE THREAD

**Issue by Jagpreet153** [VaibhavArora314/StyleShare#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The privacy policy ,cookie policy and terms and condition are routed to a same page it should be on different pages

### Expected behavior

There should be different pages for all the three links

### Add ScreenShots

![Screenshot 2024-06-18 080046](https://github.com/VaibhavArora314/StyleShare/assets/119691733/1df8078d-9a1c-45bf-9e1a-acedc4734591)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
hey @Jagpreet153 it is what @VaibhavArora314 plan .
