### ISSUE TITLE
Show a preview of the component posted by users so others can see how it looks.

### ISSUE THREAD

**Issue by Parth18Shah** [VaibhavArora314/StyleShare#26]
This will help them decide if they want to use it or not. 
Please assign me this enhancement under gssoc'24.

**Comment by VaibhavArora314** [comment]
how are you planning to implement this?

**Comment by Parth18Shah** [comment]
Initially, I plan to take an easier approach, dynamically inject the CSS code, and render it (perhaps by using dangerouslySetInnerHTML, which obviously will include me cleaning the code to reduce the security risk this can pose). Subsequently, I plan to research more methods to improve this feature to provide a more secure and faster way to render the previews. Apologies if you were expecting a more advanced approach. This is the only approach I am aware of now, and I will be open to any suggestions from your end. It will be a crucial feature to add to your application.

**Comment by Parth18Shah** [comment]
On basic parsing of the net, I found react-jsx-parser and html-react-parser, which could be explored further by me after implementing the basic approach mentioned by me above. Please allow me to try both approaches (i.e., the first one being the easier one to introduce this feature and the second one improving it). let me know if I can create two PRs for it(if both work).

**Comment by VaibhavArora314** [comment]
Sure go ahead. As for the second part, you can later raise another issue for enhancing the preview feature after implementing this.

**Comment by supriyajathar** [comment]
<img width="563" alt="Screenshot 2024-05-29 200107" src="https://github.com/VaibhavArora314/StyleShare/assets/116477978/a9cf9658-4a96-41ff-b75a-53adde650469">

**Comment by Parth18Shah** [comment]
Sure, that works. Thanks!
