### ISSUE TITLE
Enhance the sign in and sign up form

### ISSUE THREAD

**Issue by supriyajathar** [VaibhavArora314/StyleShare#27]
Proper formatting for sign-in and signup buttons and visibility for labels for the input text field.

**Comment by supriyajathar** [comment]
label of input text and due to dark background placeholder have poor visibility.
Please assign me this enhancement under gssoc'24.

**Comment by supriyajathar** [comment]
<img width="563" alt="Screenshot 2024-05-29 200107" src="https://github.com/VaibhavArora314/StyleShare/assets/116477978/cde41866-bae0-45ef-a92f-57392f937efb">

**Comment by VaibhavArora314** [comment]
this is what I see in the live deployment

![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/1027745e-0a2c-4013-bc06-9160dfd56744)

**Comment by supriyajathar** [comment]
<img width="794" alt="Screenshot 2024-05-30 162249" src="https://github.com/VaibhavArora314/StyleShare/assets/116477978/803edcd1-f8ff-49f4-9d30-963d76a10e8a">
But here it is not showing the proper button formatting also, the sign-in and sign-up buttons are not aligned.

**Comment by VaibhavArora314** [comment]
As far as i can understand the website is not loading properly on your local machine, try clearing the cache or open in a different browser or incognito.
