### ISSUE TITLE
[Feature Request]: Add category for feedback

### ISSUE THREAD

**Issue by AkhilaSunesh** [VaibhavArora314/StyleShare#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the contact form, adding a dropdown will ease the effort of the users.
![WhatsApp Image 2024-06-14 at 15 12 33_7ea25036](https://github.com/VaibhavArora314/StyleShare/assets/140897461/5e30eec6-67d2-4961-a8dd-71824f6e3408)
When the user clicks on other, the user will be asked to type in the subject.
![image](https://github.com/VaibhavArora314/StyleShare/assets/140897461/9e5e762c-283f-4ae6-a09e-56cda1c2562b)

### Use Case

easy for feedback segregation

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
the contact form is just a dummy form so I don't think this is needed
