### ISSUE TITLE
[Feature Request]: Add hover effects on cards under section  Our Code Editor

### ISSUE THREAD

**Issue by zalabhavy** [VaibhavArora314/StyleShare#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add some scale and transition so it will looks good.

### Use Case

user friendly website.

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/126322584/19c7e042-b356-463c-8498-9b38cbfa0c14)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@VaibhavArora314 Please assign me !

**Comment by manikumarreddyu** [comment]
> @VaibhavArora314 Please assign me !

Hey  @zalabhavy mak it responsive for all sizes ...which I created it i forget to make it responsive...I mean text size is not responsive...I hope you will do that..
Thank you .!
