### ISSUE TITLE
[Feature Request]: Error 404 page

### ISSUE THREAD

**Issue by taneeshaa15** [VaibhavArora314/StyleShare#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of error 404 page.

### Use Case

I will add error 404 page so that the user can be redirected to homepage and can get access to other resources.

### Benefits

1.) Saves time of user.
2.) Becomes user friendly.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by taneeshaa15** [comment]
@VaibhavArora314 Please assign me this issue under gssoc'24 level 2.

**Comment by VaibhavArora314** [comment]
404 page already exists
