### ISSUE TITLE
[Bug]: Language is not changing for all the components

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

changes should be made in locals/languages json files

### Expected behavior

it looks good

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/f8dd982f-34ae-4ff9-ba5f-9610b25114d1)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/f46750bb-4c62-4e62-9eff-b27a375706e0)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/25ba72a9-b459-41ad-b985-c46b0ddaf99e)
![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/d229861b-556b-4e04-917e-738c6fe8d156)

### On which device are you experiencing this bug?

Android, iPhone, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
the components that were added later do not have corresponding translations. do you have any permanent solution for this? like some language convertor which works like google translate.

**Comment by manikumarreddyu** [comment]
I will look into it,if there are any alternatives..assign me

**Comment by manikumarreddyu** [comment]
As of now there are no alternative for this..everybody is using i18 Library only
If there is any other alternative just update me..

**Comment by VaibhavArora314** [comment]
> As of now there are no alternative for this..everybody is using i18 Library only If there is any other alternative just update me..

For now, you can add translations for all the components missing it.
