### ISSUE TITLE
[Bug]: Home Page code editor Section is not responsive

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

for all screen sizes the text size is same..it is looking ugly

### Expected behavior

it must me responsive for all screen sizes

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/133508962/3001b90e-e1fe-469a-807a-ee1ea119f909)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
it looks responsive to me. can you please explain in more detail?
