### ISSUE TITLE
[Feature Request]: Signin/singnup with github

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Login with github will be an wonderful feature

### Use Case

It helps many users login easily

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
lets first implement google auth functionality then you can work on this
