### ISSUE TITLE
[Feature Request]: Adding "ABOUT US" button in the navbar and creating separate about us page.

### ISSUE THREAD

**Issue by HarshitGupta1511** [VaibhavArora314/StyleShare#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add "about us" button on navbar which is currently not present, that will help user to directly reach the about us page , I also want to create attractive about us page and link it to the navbar button.

please assign this task to me @va

### Use Case

this feature will help user to jump directly to the "about " page if they want to read about from the navbar only, now user have to scroll down to reach there.

### Benefits

easy navigation to about page for users

### Add ScreenShots

<img width="1349" alt="Screenshot 2024-06-23 at 9 58 07 PM" src="https://github.com/VaibhavArora314/StyleShare/assets/120268295/eba2ad9f-8a54-4b66-bb0b-2d1c4b6929c2">

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
A separate about us page already exists and is linked in the footer. Also, an about section also exists in the homepage so I don't think it is needed to an about us link in navbar.
