### ISSUE TITLE
[Feature Request]: Adding follow option in postcard itself

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As of now we just had who has created post in the post card..we dont have follow option from that

### Use Case

we allow users to have follow option from post card

### Add ScreenShots

<img width="296" alt="image" src="https://github.com/VaibhavArora314/StyleShare/assets/133508962/df7e04e5-3c39-41e1-90cb-916710961bf6">

it is static now
i want to add follow option like shown below

<img width="279" alt="image" src="https://github.com/VaibhavArora314/StyleShare/assets/133508962/02302400-a99d-46a1-a3c2-dbb3263f8d3a">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
rather than follow button here we can have a profile link here
