### ISSUE TITLE
[Feature Request]: Adding some description below logo in footer

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

description

### Use Case

it looks nice

### Benefits

<img width="311" alt="image" src="https://github.com/VaibhavArora314/StyleShare/assets/133508962/71d0b20c-4bdc-4211-b704-14cde27c5693">

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
make sure it is responsive and maybe you can hide it on smaller devices
