### ISSUE TITLE
[Feature Request]: PAGE progress bar around scroll to top button

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Ii is innovative idea

### Use Case

excellent ui

### Add ScreenShots

<img width="87" alt="image" src="https://github.com/VaibhavArora314/StyleShare/assets/133508962/8c7f8249-f547-4def-a9c1-d733798236a0">

the thing which is above the goto top button is custom cursor with gradient colors it is looking excellent.
i want to make this feature for our website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
a progress bar issue was already raised for progress bar in navbar and I don't think someone is gonna notice it there
