### ISSUE TITLE
[Feature Request]: wave like animation for footer

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

as of now our footer is looking plain.

### Use Case

wave like animation makes our website more attractive

### Add ScreenShots

https://github.com/VaibhavArora314/StyleShare/assets/133508962/de279ba7-d9c9-4273-ba10-a26f711fa5c5

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@manikumarreddyu Bro it will look like some disney website 🗿

**Comment by VaibhavArora314** [comment]
lets keep the website ui simple and I don't think this is needed
