### ISSUE TITLE
[Feature Request]: Adding Admin approach to whole style share webapp

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@VaibhavArora314 I am thinking of this feature from a long time, i want to create this feature with admin dashboard and all so can you please suggest me the road map like how many pr and issue with there feature like for users,posts,comments,likes,dashboard C.R.U.D operations and all like a admin have.

### Use Case

With this feature their will be a admin who will manage the whole webapp effectively without any issues.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
There is a need for this feature because if any create duplicate or dummy content admin can able to remove easily..so that app will be productive in nature

**Comment by MeetDOD** [comment]
> There is a need for this feature because if any create duplicate or dummy content admin can able to remove easily..so that app will be productive in nature

You can't go to the database and do delete and all it's a headache and time consuming, what if there is malicious users and also spammming the comment or unnecessary posts then what you will do ?
Go in database and manully delete it 💀 or you have a nice complete dashboard to do it ! what you choose ?

**Comment by VaibhavArora314** [comment]
I am thinking of creating a new react app for this which can also be served via express sever. I will add the basic setup for that, and then you can start working on this.

Also, let's break this into multiple subtasks for now:
1. create an additional parameter in the user model for isAdmin which is false for all users by default and a sign-in dashboard for admin users with a route /sign-in. once signed in the user can see a blank page for now. This can be considered a level 2 since a simple sign-in route and sign-in page needed to be added.
2. Add a user menu in the admin panel where the admin user can see all the users with their username, email, verified status, an option to make them admin user, and lastly an option to block the user. Once the user is blocked, the user cannot sign in. This can be assigned level 2.

I will tell you more features, for now, implement these.
Depending on the work, labels can later be discussed after you implement the prs.

**Comment by MeetDOD** [comment]
> I am thinking of creating a new react app for this which can also be served via express sever. I will add the basic setup for that, and then you can start working on this.
> 
> Also, let's break this into multiple subtasks for now:
> 
> 1. create an additional parameter in the user model for isAdmin which is false for all users by default and a sign-in dashboard for admin users with a route /sign-in. once signed in the user can see a blank page for now. This can be considered a level 2 since a simple sign-in route and sign-in page needed to be added.
> 2. Add a user menu in the admin panel where the admin user can see all the users with their username, email, verified status, an option to make them admin user, and lastly an option to block the user. Once the user is blocked, the user cannot sign in. This can be assigned level 2.
> 
> I will tell you more features, for now, implement these. Depending on the work, labels can later be discussed after you implement the prs. If this becomes too much work, you can split the tasks with someone else and collaborate with them on this issue.

Okay, I will work on the user admin feature and if help needed I will involve @manikumarreddyu in this feature respectively. Just provide me the basic setup and we good to go 🙂

**Comment by VaibhavArora314** [comment]
I have added the admin folder, you guys can start working on this.

**Comment by MeetDOD** [comment]
@VaibhavArora314 should I create new issue and work on it ? like that way we can avoid confusion and it will be structured manner.

**Comment by manikumarreddyu** [comment]
i think creating new issues is better

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 should I create new issue and work on it ? like that way we can avoid confusion and it will be structured manner.

sure, go ahead

**Comment by manikumarreddyu** [comment]
hey @VaibhavArora314 created new issue with same title .is it ok ?

**Comment by VaibhavArora314** [comment]
> hey @VaibhavArora314 created new issue with same title .is it ok ?

same titles can be confusing, rather create issues with the title of the feature being implemented

**Comment by manikumarreddyu** [comment]
> > hey @VaibhavArora314 created new issue with same title .is it ok ?
> 
> same titles can be confusing, rather create issues with the title of the feature being implemented

i will chane it to admin approach..is it ok

**Comment by MeetDOD** [comment]
@manikumarreddyu bro you don't create issues on admin i will tell you if help needed 😄 we will work in the same issues only

**Comment by manikumarreddyu** [comment]
okay @MeetDOD
