### ISSUE TITLE
Add Icons to Navbar

### ISSUE THREAD

**Issue by sailaja-adapa** [VaibhavArora314/StyleShare#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add icons to Navbar to make the website to look attractive 

Can you please assign me this issue under gssoc'24 @VaibhavArora314 

### Use Case

![jj](https://github.com/VaibhavArora314/StyleShare/assets/161804629/6f067cd9-826c-47c5-9f02-0c3acde436ef)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
make sure it is responsive

**Comment by sailaja-adapa** [comment]
yeah okk @VaibhavArora314

**Comment by MeetDOD** [comment]
@VaibhavArora314 assign to me i will do it today only 👍
