### ISSUE TITLE
[Feature Request]: Adding login for admin 

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Creating an additional parameter in the user model for isAdmin which is false for all users by default and a sign-in dashboard for admin users with a route /sign-in. once signed in the user can see a blank page for now.

### Use Case

Admin flexibility.

### Benefits

Admin usage

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@VaibhavArora314 if admin login it should navigate by default to dashboard but what about navbar what links you want on top ?

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/475fedd7-6fa1-40ee-b255-395cb4729b18)

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 if admin login it should navigate by default to dashboard but what about navbar what links you want on top ?
> 
> ![image](https://private-user-images.githubusercontent.com/120380073/344233351-475fedd7-6fa1-40ee-b255-395cb4729b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTk4NDcsIm5iZiI6MTcxOTgxOTU0NywicGF0aCI6Ii8xMjAzODAwNzMvMzQ0MjMzMzUxLTQ3NWZlZGQ3LTZmYTEtNDBlZS1iMjU1LTM5NWNiNDcyOWIxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNzM5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTNkNDRiOTQ2OWUzMmE3MjAxNGU2N2NhYmEyNDExODZmNzI3NjM5YWMwYTMzNzZhYjgwNmE4N2EwMzAxZDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x7g8SUb29GwsvAznyld46IHcqmjcLd21IAY3mjwe8h8)

you can add a basic navbar in a separate pull request

**Comment by VaibhavArora314** [comment]
@MeetDOD instead of a navbar you can create a sidebar for logged-in users like you posted in #337 and for users which are not logged in, they only see sign in page

**Comment by MeetDOD** [comment]
> @MeetDOD instead of a navbar you can create a sidebar for logged-in users like you posted in #337 and for users which are not logged in, they only see sign in page

Ya I do that only but the default navbar which user can see what about it, should i show all the fields or just the dashboard only ?

**Comment by VaibhavArora314** [comment]
> > @MeetDOD instead of a navbar you can create a sidebar for logged-in users like you posted in #337 and for users which are not logged in, they only see sign in page
> 
> Ya I do that only but the default navbar which user can see what about it, should i show all the fields or just the dashboard only ?

after login, the user should only be able to see dashboard since there is nothing else in the admin panel other than the dashboard
