### ISSUE TITLE
[Feature Request]:  Adding proper comments to the files 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [VaibhavArora314/StyleShare#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will add a proper comments to the files so that it becomes easy for the new developer to udnerstand the code properly 

### Use Case

This will surely help to understand the logic of the code properly .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
so you will add comments to the already existing code?

**Comment by akbatra567** [comment]
As a clean code practice, code should be readable on its own and we should always avoid comments.

If the purpose is to making it easier for the new developer to understand the code properly. You can look at updating documentation on getting started docs, updating api documentation and add some learning resources on to learn pre-requisites for the project.

@Ayushmaanagarwal1211
