### ISSUE TITLE
[Feature Request]:  Email on Contact Us

### ISSUE THREAD

**Issue by sivaprasath2004** [VaibhavArora314/StyleShare#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

If i want to implement to the `Contact us` page.

## **What Feature are add the Contact Us page .**
-  If the user can be suggestion to give `Example : This is project is super` in this content type to send also `user` mail address we want to implement the return to send `Thank you for contacting..` in user mail address.

## How to Implement
-  **Backend**
-  Nodemailer and Mongodb

## How to Implement NodeMailer
```
async function sendOTPEmail(email, otp) {
    let transporter = nodemailer.createTransport({
        service: 'gmail',  // Adjust this according to your email service
        auth: {
            user: 'your-email@gmail.com',
            pass: 'your-email-password'
        }
    });

    let info = await transporter.sendMail({
        from: '"OTP Service" <your-email@gmail.com>',
        to: email,
        subject: 'Your OTP Code',
        text: `Your OTP code is: ${otp}`
    });

    console.log('Message sent: %s', info.messageId);
}
```

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sivaprasath2004** [comment]
@VaibhavArora314  , I'm telling about user can `Contact Us` contacted some suggestions .
- We will implement to the user Mail address `Thank you  for Contacting` mail.
- please assign me..

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314  , I'm telling about user can `Contact Us` contacted some suggestions .
> - We will implement to the user Mail address `Thank you  for Contacting` mail.
> - please assign me..

Ok go ahead, add an email functionality for this. Also pass details of the message written in contact form in case the user wants to check in future.

**Comment by VaibhavArora314** [comment]
The mailing functionality is already implemented for some other use cases, take reference from there if needed.

**Comment by sivaprasath2004** [comment]
@VaibhavArora314 please give Discord channel name and other social media profile link

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 please give Discord channel name and other social media profile link

the discord channel has the same name as the project in the server.
