### ISSUE TITLE
[Feature Request]: Improve search posts

### ISSUE THREAD

**Issue by Parth18Shah** [VaibhavArora314/StyleShare#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, users can input only one character at a time since the posts are filtered with each character typed. I plan to make the process more dynamic by displaying the search bar while posts are still loading and updating the displayed posts based on the current input.

### Use Case

Improve UX for searching posts.

### Benefits

Improve UX for searching posts.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
can you please explain more about this

**Comment by Parth18Shah** [comment]
Hello, apologies for the delay in my response. I had reached out to you on Discord, but I will reply here as well. Basically, my issue included the bug covered by Meet in his issue #362. I noticed that he had checked the option of "I have searched the existing issues" but never mentioned my issue. Now, I don't mind him covering a particular task of mine even though I made an issue of it before he did, but I understand since I could not respond in time to your comment on my issue. If you want, you could close this issue, or I could try making the search dynamic i.e. remove the button next to the input field, which has its own pros and cons.

**Comment by VaibhavArora314** [comment]
> Hello, apologies for the delay in my response. I had reached out to you on Discord, but I will reply here as well. Basically, my issue included the bug covered by Meet in his issue #362. I noticed that he had checked the option of "I have searched the existing issues" but never mentioned my issue. Now, I don't mind him covering a particular task of mine even though I made an issue of it before he did, but I understand since I could not respond in time to your comment on my issue. If you want, you could close this issue, or I could try making the search dynamic i.e. remove the button next to the input field, which has its own pros and cons.

sorry for the late response
as for the search functionality, I think you can implement order functionality like users can order posts by date or reactions. Currently, it is implemented by the count of reactions so you will have to modify that API to serve based on date if the user specifies else by default show by reactions.

**Comment by VaibhavArora314** [comment]
if you are willing to implement this you can reply here, I will assign you this

**Comment by Parth18Shah** [comment]
Sure, I can implement it. So do you want me to create a separate option next to the search bar to sort by a particular type or change the order search result itself. The former will be better, in my opinion, since it will provide the users with more options to search for a particular post they want.

**Comment by Parth18Shah** [comment]
Understood, I will start working on it. Thanks for the clarification.

**Comment by Parth18Shah** [comment]
<img width="369" alt="image" src="https://github.com/user-attachments/assets/d49cbe9e-3b95-44c2-a700-a22ffed50359">
<img width="380" alt="image" src="https://github.com/user-attachments/assets/983dfeaf-d97f-4c0d-93de-d8a670a94e4e">

notice that there is a background strip behind the text 'Modal' and 'modal' that goes across the width .. although they aren't very visible, they aren't needed, and once you notice them, they seem to be distracting.

**Comment by Parth18Shah** [comment]
Could you please help me with the sorting on the server side.
I am currently sending an additional parameter to the getPostsWithPagination controller to handle sorting. In the controller, I have generalized the orderBy query based on the sortBy parameter received. The code snippet is as follows:

const orderPosts = sortOrder === 'reactions' ? {
  reactions: {
    _count: 'desc'
  }
} : {
  createdAt: 'desc'
};

Unfortunately, the orderBy query is unable to accept a variable as input, as either reactions or createdAt will be undefined in one of the cases. How should I proceed to handle this sorting dynamically on the server side?

**Comment by VaibhavArora314** [comment]
> Could you please help me with the sorting on the server side. I am currently sending an additional parameter to the getPostsWithPagination controller to handle sorting. In the controller, I have generalized the orderBy query based on the sortBy parameter received. The code snippet is as follows:
> 
> const orderPosts = sortOrder === 'reactions' ? { reactions: { _count: 'desc' } } : { createdAt: 'desc' };
> 
> Unfortunately, the orderBy query is unable to accept a variable as input, as either reactions or createdAt will be undefined in one of the cases. How should I proceed to handle this sorting dynamically on the server side?

This may help https://stackoverflow.com/questions/73680309/dynamic-sorting-in-prisma-and-typed-queries

**Comment by Parth18Shah** [comment]
Yes, thank you. Wrapping orderBy with a const worked. Thanks.

**Comment by Parth18Shah** [comment]
I will try adding an option to sort in ascending or descending order for both of those options.
