### ISSUE TITLE
[Bug]: Filter by tag is not working as intended 

### ISSUE THREAD

**Issue by Parth18Shah** [VaibhavArora314/StyleShare#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, adding a tag as a search filter is filtering posts by that tag as a keyword within the entire data. Instead, it should filter posts based solely on the tags assigned to them.

### Expected behavior

Added tag will filter the posts with that tag assigned to it.

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
an API request is sent with tags in the usePosts hook which filters posts with at least one of the passed tags. I think this is the logic and keyword searching is done for the search text written by the user. if I am wrong, please correct me.

**Comment by Parth18Shah** [comment]
Yes you're right but shouldn't we just search the keyword in the tags associated to the posts instead of a search across all of its details.

**Comment by Parth18Shah** [comment]
Hey there, I believe that someone has fixed the bug I tried to describe above. Now, the filter by tags works as intended, filtering by tags associated with the posts and nothing else (name, description). So you could check and test to see if it still exists, and if it doesn't, then you could close it.

**Comment by VaibhavArora314** [comment]
> Hey there, I believe that someone has fixed the bug I tried to describe above. Now, the filter by tags works as intended, filtering by tags associated with the posts and nothing else (name, description). So you could check and test to see if it still exists, and if it doesn't, then you could close it.

you can work on this since another bug is present now
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/5eb1b5ff-93a1-4a70-b11d-6b3200bbfb98)

**Comment by Parth18Shah** [comment]
Sure, I can do it. Thanks. Could you confirm the tag filter inputted by you to get these results?

**Comment by VaibhavArora314** [comment]
> Sure, I can do it. Thanks. Could you confirm the tag filter inputted by you to get these results?

actually, that allPosts.addTag was already present by default

**Comment by Parth18Shah** [comment]
What does it mean? It doesn't make sense to be displayed, right?

**Comment by VaibhavArora314** [comment]
> What does it mean? It doesn't make sense to be displayed, right?

yes, that's the issue. we need to remove it and if possible below selected tags in filter we can show some options for users to select tags from

**Comment by Parth18Shah** [comment]
Can't we modify the placeholder to show some sample keywords that the users could use to filter by tag?

**Comment by VaibhavArora314** [comment]
> Can't we modify the placeholder to show some sample keywords that the users could use to filter by tag?

yes, you can see how we are getting some of these on the home page and reuse that logic
![image](https://github.com/user-attachments/assets/2e61c5ef-53bf-407d-b164-3cd7f8a20722)

**Comment by Parth18Shah** [comment]
Got it

**Comment by Parth18Shah** [comment]
I noticed that some bugs discussed here have already been resolved. So, I will be working on the following things over here:
- Mainly add a few tags in the placeholder as an example
- Modify the code layout not to show the previous and next button if no results are found
- Modify the styling of the text on the posts displayed to avoid the dark blue/white strip behind the text

Could you please confirm if you want to keep the filter by tags case insensitive? Currently, we are storing the input tags in lowercase, which will skip over the posts that contain the same tags but with different characters capitalized. For example, a post with the tag 'Form' won't show currently if we filter by 'form' or even 'Form' tag.

**Comment by VaibhavArora314** [comment]
> I noticed that some bugs discussed here have already been resolved. So, I will be working on the following things over here:
> 
> * Mainly add a few tags in the placeholder as an example
> * Modify the code layout not to show the previous and next button if no results are found
> * Modify the styling of the text on the posts displayed to avoid the dark blue/white strip behind the text
> 
> Could you please confirm if you want to keep the filter by tags case insensitive? Currently, we are storing the input tags in lowercase, which will skip over the posts that contain the same tags but with different characters capitalized. For example, a post with the tag 'Form' won't show currently if we filter by 'form' or even 'Form' tag.

Sure go ahead. Just one question, which dark blue/white strip?

**Comment by Parth18Shah** [comment]
<img width="386" alt="image" src="https://github.com/user-attachments/assets/f4b05e10-8862-4ccc-a0ed-8b8bf266be4f">

<img width="370" alt="image" src="https://github.com/user-attachments/assets/d0b3ca8f-19f3-4e6e-8a9c-488f432b391c">

notice that there is a background strip behind the text 'Modal' and 'modal' that goes across the width .. although they aren't very visible, they aren't needed, and once you notice them, they seem to be distracting.

Could you please comment on the case insensitive part for the filtering?

**Comment by VaibhavArora314** [comment]
> <img alt="image" width="386" src="https://private-user-images.githubusercontent.com/46682842/352023955-f4b05e10-8862-4ccc-a0ed-8b8bf266be4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDg1NzEsIm5iZiI6MTcyMjAwODI3MSwicGF0aCI6Ii80NjY4Mjg0Mi8zNTIwMjM5NTUtZjRiMDVlMTAtODg2Mi00Y2NjLWEwZWQtOGI4YmYyNjZiZTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE1Mzc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Zjk0OWE5ZWU2MzJhZjg0M2VhMWUzYmEzYTJiYzRiNTI0MjA2YzFkZTExMjY0MWRmY2M4ZDRlYTNlMmE5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1qFq_uegpr3bKKWn4D95HZ6mMioFk61Ra2WbANiLQfg"> <img alt="image" width="370" src="https://private-user-images.githubusercontent.com/46682842/352024073-d0b3ca8f-19f3-4e6e-8a9c-488f432b391c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDg1NzEsIm5iZiI6MTcyMjAwODI3MSwicGF0aCI6Ii80NjY4Mjg0Mi8zNTIwMjQwNzMtZDBiM2NhOGYtMTlmMy00ZTZlLThhOWMtNDg4ZjQzMmIzOTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE1Mzc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNGY0MWRmY2VlNTkxM2VmODYzOTEzZDQwMmQyNDUzNGIyMGUxMjQ4Njc5N2UyY2MyNTczZTE0OTQ0OGMwYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRISBD7Jvkam8Kkj5mmPfmlF8A6MZsg0EIOta0dR-zA">
> notice that there is a background strip behind the text 'Modal' and 'modal' that goes across the width .. although they aren't very visible, they aren't needed, and once you notice them, they seem to be distracting.
> 
> Could you please comment on the case insensitive part for the filtering?

The filtering should be case insensitive and for the background, you can remove the strips.

**Comment by Parth18Shah** [comment]
Understood, thanks for your response. Sorry for the delay in my response.
