### ISSUE TITLE
[Feature Request]: Adding the tilty effect to all cards at home page.

### ISSUE THREAD

**Issue by happyrao78** [VaibhavArora314/StyleShare#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Using react tilty library for  the same.

### Use Case

na

### Benefits

Will enhance the UI for cards particularly.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
can you provide a demo for this

**Comment by VaibhavArora314** [comment]
since no response closing this
