### ISSUE TITLE
[Feature Request]: Creating admin login / logout in frontend

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Sign-in dashboard for admin users with a route /sign-in. once signed in the user can see a blank page for now.
In this the frontend will do the login/logout functionality with the backend logic and then integrating with tha admin folder.

### Use Case

Admin flexibility.

### Benefits

Admin usage

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@Ultimateutkarsh11 can you tell me how should i code in admin folder i have coded the functionality but i don't lnow where to code in admin like i do npm run build/ how should i run them ?

Please explain me in brief
Thank you !

**Comment by Ultimateutkarsh11** [comment]
> @Ultimateutkarsh11 can you tell me how should i code in admin folder i have coded the functionality but i don't lnow where to code in admin like i do npm run build/ how should i run them ?
> 
> Please explain me in brief Thank you !

@VaibhavArora314  has already uploaded a basic template, you can continue in that further.
