### ISSUE TITLE
[Feature Request]: Proper UI and Interactivity for the entire About Us Page

### ISSUE THREAD

**Issue by r7projects-shayan** [VaibhavArora314/StyleShare#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The About Us Page has no interactive and sleek animations and does not have a proper UI, there are less gaps and less spacings and the texts are almost overlapping in smaller devices. 

### Use Case

Proper Ui ensures better User Experience and improves readability of the website.

Sleek animations and lottie files will make the Styleshare more interactive and fun to visit.

### Add ScreenShots

![Screenshot 2024-07-01 005223](https://github.com/VaibhavArora314/StyleShare/assets/167475552/db26ad17-698e-46bc-800f-aaadbb1e9071)
![Screenshot 2024-07-01 005733](https://github.com/VaibhavArora314/StyleShare/assets/167475552/99983d9b-1c75-436e-bdd6-38ff9e71a2b2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by r7projects-shayan** [comment]
@VaibhavArora314 kindly assign me this issue

**Comment by VaibhavArora314** [comment]
@r7projects-shayan any updates?

**Comment by r7projects-shayan** [comment]
@VaibhavArora314 I'm modifying the finalized code, will submit it soon by tomorrow
