### ISSUE TITLE
[Bug]: Elements are overlapping with each other in the posts page

### ISSUE THREAD

**Issue by r7projects-shayan** [VaibhavArora314/StyleShare#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The elements are overlapping with each other and the navbar in the posts page in smaller and very small devices.

### Expected behavior

No overlap of elements and each element should be interactive enough independent of the other.

### Add ScreenShots

![Screenshot 2024-07-01 005936](https://github.com/VaibhavArora314/StyleShare/assets/167475552/ba13d12c-a059-453a-a2d8-a99d47a4b38d)
![Screenshot 2024-07-01 010006](https://github.com/VaibhavArora314/StyleShare/assets/167475552/5f195c19-8de2-4720-a8cf-9e56bd265048)

### On which device are you experiencing this bug?

Android, iPhone, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by r7projects-shayan** [comment]
@VaibhavArora314 I know how to fix this, please assign this to me, I will start working on it right away

**Comment by VaibhavArora314** [comment]
a similar issue already exists #336
