### ISSUE TITLE
Modify Home page UI

### ISSUE THREAD

**Issue by root-0101** [VaibhavArora314/StyleShare#35]
It would be great if we enhance the UI of the home page and add hero image, which increase the user experience and engagement 

![Screenshot 2024-05-30 184925](https://github.com/VaibhavArora314/StyleShare/assets/142779809/ed6c050f-5966-4978-8047-4c1ce49fe08c)

**Comment by VaibhavArora314** [comment]
modify the header text and add an image on the right side of the text which disappears for smaller devices.
make sure your changes do not overlap with #4 where sections of the about page and recent posts are to be added.
