### ISSUE TITLE
[UX Change] Make the Post Card Clickable

### ISSUE THREAD

**Issue by akbatra567** [VaibhavArora314/StyleShare#350]
## UX Change Requested
* While we hover over the card it gives an impression that the whole card is clickable and when we try clicking it. It doesn't function that way. 

## Impact
* It gives a wrong impression to the user, making it hard for user to understand when using the application for the first time.
* Makes user do extra mouse moment to reach the `Read More` button.

## Screenshot: 
![Screenshot 2024-07-01 at 10 43 27 PM](https://github.com/VaibhavArora314/StyleShare/assets/59093007/d98db00b-4851-4455-81ca-ad12467986b8)

## Acceptance Criteria
* As a user when I hover on the Post Card, it should:
  * Retain the current hover effect
  * Is clickable and redirects the same way `Read More` works.
  
cc: @VaibhavArora314, Do have a look ? 
- If this looks good, it is open for anyone to pick.

**Comment by ShagunSharma17** [comment]
Can you assign this task to me?

**Comment by akbatra567** [comment]
Great @ShagunSharma17, Thanks for signing up for this task.

**Comment by VaibhavArora314** [comment]
@ShagunSharma17 any updates?

**Comment by MeetDOD** [comment]
@VaibhavArora314 assign this to me I will do it 👍

**Comment by Vaibhav-kesarwani** [comment]
@VaibhavArora314 Please assign this to me

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 assign this to me I will do it 👍

Let's give new contributors some chance also. I hope you understand.

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 assign this to me I will do it 👍
> 
> Let's give new contributors some chance also. I hope you understand.

I have no problem, @VaibhavArora314 I agree with you 💯

**Comment by Vaibhav-kesarwani** [comment]
Thanks @VaibhavArora314
