### ISSUE TITLE
[Bug]:  In mobile screen navbar section sing in/sing up and mode change button not have proper margin

### ISSUE THREAD

**Issue by zalabhavy** [VaibhavArora314/StyleShare#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/VaibhavArora314/StyleShare/assets/126322584/dc04af11-d81e-43f0-80e8-d7d1beac36de)

**Here you can see home , post and leaderboard have margin but buttons not have** 

### Expected behavior

All navbar items should have same margin

### Add ScreenShots

NA

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@VaibhavArora314 Please assign me !

**Comment by VaibhavArora314** [comment]
this was not resolved why is it marked completed?
