### ISSUE TITLE
[Feature Request]: Adding captcha in all authentication pages

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will create a this captcha featur for all the three authentication places namely,

1. User login
2. User Register
3. Admin Login

repectively.

So, the captcha will helps to differentiate between humans and bots in style share webapp.

### Use Case

Security

### Benefits

Authentication

### Add ScreenShots

Example:

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/eb5ebfe2-7373-494e-83de-d31a3d76ddf5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
How are you planning to implement this? Is there a library for this?

**Comment by MeetDOD** [comment]
> How are you planning to implement this? Is there a library for this?

Ya there are packages but I will implement it by myself only.
I will generate random string with the js and take input from the user if random string = input then they can submit or else incorrect recaptcha like that
