### ISSUE TITLE
[Feature Request]: Adding multilanguage in admin panel

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will implement the multi language functionality in admin panel so that in future or in current if the admin changes other admin can manage the dashboard without having any language barriers.
So, i will implement this feature similar to that of style share app.

### Use Case

Multi Language

### Benefits

removing Language barrier

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/f7981615-2028-430e-ac97-51bd583e5bea)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@VaibhavArora314 I will implement this feature when the all admin features are completed. so, that again and again language will not change and the result will be at the end and completed.

**Comment by MeetDOD** [comment]
But in future if admin changes in that scenario !

**Comment by VaibhavArora314** [comment]
> But in future if admin changes in that scenario !

ok, sure
