### ISSUE TITLE
[Feature Request]: Creating API/fetching in card status 

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. In this i will create a API for fetching the total users and api which calculate the total posts in style share uploaded till now.
2. and showing in the style card at main dashboard page.
3. Also i will add extra card which calculate the visits and page view i will rename it.
4. Page views => when user reload the page.
5. Visits => when user will open in new tab. (For this i have to create two api)
6. Total Api's will be 4.

### Use Case

Admin Analytics

### Benefits

Tracking

### Add ScreenShots

Eg:

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/37070afa-56af-4114-8714-4043a1a33980)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
how will you calculate page views

**Comment by MeetDOD** [comment]
> how will you calculate page views

I will take reference from this youtube video => [https://youtu.be/mtuYmm2ITvI?si=wepoQVC7BX0yXxqT](url)

**Comment by MeetDOD** [comment]
> I am thinking of only adding visits to the website and for that, a simple middleware needs to be added here which updates website visits.
> 
> https://github.com/VaibhavArora314/StyleShare/blob/93b5cb29aee44c2e9e3a155852d10a8c5e653432/backend/src/app.ts#L17
> 
> 
> what do you think?

Okay i will not add the views, i will consider visits only
