### ISSUE TITLE
[Feature Request]: To add new features to profile page such as avatars, tech stacks, etc

### ISSUE THREAD

**Issue by ayush-848** [VaibhavArora314/StyleShare#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The profile avatar can be changed by user, user can also add his/her tech stacks such as tailwind, javascript, react, tec

### Use Case

The profile avatar can be changed by user, user can also add his/her tech stacks such as tailwind, javascript, react, tec

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
in the profile avatar, will you allow the user to add images? or will you provide some predefined avatars the user can choose from?

**Comment by ayush-848** [comment]
> in the profile avatar, will you allow the user to add images? or will you provide some predefined avatars the user can choose from?

My initial thought was to add some predefined gendered avatars and user will choose one of them

**Comment by VaibhavArora314** [comment]
> > in the profile avatar, will you allow the user to add images? or will you provide some predefined avatars the user can choose from?
> 
> My initial thought was to add some predefined gendered avatars and user will choose one of them

Sure, go ahead with this approach.

**Comment by ayush-848** [comment]
> in the profile avatar, will you allow the user to add images? or will you provide some predefined avatars the user can choose from?

Well the part will be to implement the choosing features.

Then after we can introduce many add ons

**Comment by VaibhavArora314** [comment]
I will add level label based after reviewing the complexity and work done in pull request

**Comment by ayush-848** [comment]
> I will add level label based after reviewing the complexity and work done in pull request

Sure

**Comment by ayush-848** [comment]
@VaibhavArora314 for  frontend change also Do I need to set up the backend part??

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 for  frontend change also Do I need to set up the backend part??

To test and develop the feature, you will have to setup both frontend and backend

**Comment by ayush-848** [comment]
> > @VaibhavArora314 for  frontend change also Do I need to set up the backend part??
> 
> To test and develop the feature, you will have to setup both frontend and backend

Ok ok, actually I do not have that much experience in backend and seeing all those steps were a bit overwhelming

**Comment by VaibhavArora314** [comment]
> > > @VaibhavArora314 for  frontend change also Do I need to set up the backend part??
> > 
> > To test and develop the feature, you will have to setup both frontend and backend
> 
> Ok ok, actually I do not have that much experience in backend and seeing all those steps were a bit overwhelming 

Ok so how are you planning to implement avatar and tech stack info of user since that will require you to implement new api or modify existing api for it in backend as well

**Comment by ayush-848** [comment]
> > > > @VaibhavArora314 for  frontend change also Do I need to set up the backend part??
> > > 
> > > 
> > > To test and develop the feature, you will have to setup both frontend and backend
> > 
> > 
> > Ok ok, actually I do not have that much experience in backend and seeing all those steps were a bit overwhelming
> 
> Ok so how are you planning to implement avatar and tech stack info of user since that will require you to implement new api or modify existing api for it in backend as well

I thought of saving the data,i.e, tech stack and avatar, in local storage, there by the changes will remain constant

**Comment by VaibhavArora314** [comment]
But how will this be shared to other users when they visit someone else's profile.

**Comment by ayush-848** [comment]
> But how will this be shared to other users when they visit someone else's profile.

Hmm, you are right.
Ok you can un-assign me or close the issue.

I reckon it won't be possible without backend knowledge.

**Comment by ayush-848** [comment]
btw @VaibhavArora314 The changes I will do will be in frontend>Profile.tsx
and where do I have to update the changes??
