### ISSUE TITLE
[Feature Request]: Add Google Translator Integration

### ISSUE THREAD

**Issue by AsmitaMishra24** [VaibhavArora314/StyleShare#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to request the addition of Google Translator integration into the project. This feature would significantly enhance the user experience by providing seamless translation capabilities.

### Use Case

Accessibility: Non-native speakers would find it easier to use the application.
Global Reach: Expanding the usability of the application to a global audience.
User Convenience: Simplifies the process for users needing translation services within the app.

### Add ScreenShots

![lang](https://github.com/VaibhavArora314/StyleShare/assets/146121869/7d6af48f-77a1-4efe-b432-9fd0613a77b9)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
also, remove language translation implemented using react18next while implementing this

**Comment by VaibhavArora314** [comment]
@AsmitaMishra24 any updates?

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 any updates?

My exams are going on...I will complete it by Thursday @VaibhavArora314
