### ISSUE TITLE
Update Leaderboard Logic and remove like-dislike logic

### ISSUE THREAD

**Issue by VaibhavArora314** [VaibhavArora314/StyleShare#379]
leaderboard is using likes logic which has been removed from the web app. Perform the following tasks:
1. Update the backend, and remove the like-dislike properties from the user model and anywhere else used in the application. 
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/ca015b95-823d-4d93-8468-bd3b5a6ebbe1)

2. Also, update the leaderboard logic to work on user posts' total reactions count.
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/f7a2236e-aee6-49fa-a5ad-6f4947ca6912)

**Comment by MeetDOD** [comment]
I will do this, i will update the leaderboard with the number of reactions user have , @VaibhavArora314 Assign me this !
