### ISSUE TITLE
Dynamic searching without page reloading.

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#38]
![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/9c890cdd-304b-4a90-8426-906e1e55fead)

I have an idea in search section that instead for reloading the whole page we can search the posts in the frontend part only without reloading the page like dynamically fetching the posts in frontend only.

Just need to add couple of lines in th react hook.

I am interested in it because i had done this previously also.

so, I request you to assign it to me.

**Comment by VaibhavArora314** [comment]
can you also a search input section @MeetDOD which filters it on the basis of the title and description of the post? I will make this issue level3 accordingly.

**Comment by VaibhavArora314** [comment]
Great

**Comment by VaibhavArora314** [comment]
@MeetDOD i am lowering the level to 2 because initially I thought you will use custom react hook to dynamically refresh the posts without reloading the page

**Comment by MeetDOD** [comment]
I see, no prob 👍
