### ISSUE TITLE
Navbar not Uniform in DropDown view

### ISSUE THREAD

**Issue by Utsavladia** [VaibhavArora314/StyleShare#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/VaibhavArora314/StyleShare/assets/124615886/209caaee-c311-4603-8b9d-48410ab898b3)

### Expected behavior

It should be fixed the alignment to have a good experience on all devices

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
A similar issue is being worked upon, if it's not implemented then you can work on it
