### ISSUE TITLE
[Bug]: In Privacy Policy, Terms and Conditions, Cookie Policy image takes lots of space in left side.

### ISSUE THREAD

**Issue by zalabhavy** [VaibhavArora314/StyleShare#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/VaibhavArora314/StyleShare/assets/126322584/368abf10-34be-435e-aa3a-4c7c96155a00)

**I will fix this images in same raw with title and in small size as text.
So left side's space will be utilized also in mobile screen we get better look.**

### Expected behavior

NA

### Add ScreenShots

NA

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@VaibhavArora314 Please assign me this task !

**Thank You !**

**Comment by VaibhavArora314** [comment]
how are you planning to edit this?

**Comment by zalabhavy** [comment]
@VaibhavArora314 I think to remove images from left side and put that as a small icon in same raw with Heading like 

**Privacy Policy (image as a symbol)** 

Then text so in small screen it will also looks good because of that images in small size screen it will take more space in left side.
