### ISSUE TITLE
[Feature Request]: light / dark modes for admin panel

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

light / dark modes for admin panel

### Use Case

Looks good

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
I am assuming @MeetDOD split this task with you

**Comment by MeetDOD** [comment]
> I am assuming @MeetDOD split this task with you

I told him to do this feature

**Comment by lovelymahor** [comment]
@MeetDOD Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

**Comment by MeetDOD** [comment]
> @MeetDOD Please assign it to me I want to work on this issue. Also, please add the label GSSOC and the level that you find appropriate for this issue. thank you!

Tell @VaibhavArora314 to assign, I am not the admin that's why !

**Comment by manikumarreddyu** [comment]
@VaibhavArora314  you can assign to @MeetDOD  or anyone...currently i am busy with college works.
thank you.
