### ISSUE TITLE
Enhance Home page of the website

### ISSUE THREAD

**Issue by VaibhavArora314** [VaibhavArora314/StyleShare#4]
try not to modify the navbar and footer unnecessarily as merge conflicts may arise later.

![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/5b37fba2-1660-4a63-a181-cd40be7b7e03)

There need to be added following 2 sections:
1. An about us section
2. Recent posts sections

**Comment by Amrapali06** [comment]
@Rakesh9100 can you assign me this issue

**Comment by VaibhavArora314** [comment]
hey @Amrapali06 there is no maintainer named Rakesh in this project

**Comment by VaibhavArora314** [comment]
@Amrapali06 make sure to add an about us section and recent posts section which shows some recent posts

**Comment by akshaydubey430** [comment]
can u assign me this i can enhance the home page

**Comment by Amrapali06** [comment]
what exactly are you expecting in this home page

**Comment by Amrapali06** [comment]
> @Amrapali06 make sure to add an about us section and recent posts section which shows some recent posts

okay sure , i will start working on it

**Comment by akshaydubey430** [comment]
I want some images related to the content of the website and that would be
animated images which i can apply in which text will also come or i can
also add the nav bar at the top of home page..

**Comment by VaibhavArora314** [comment]
Hey @Amrapali06 , are you not working on this anymore?

**Comment by MeetDOD** [comment]
@VaibhavArora314 I am available to help sir, i can modify the home page UI. If you assign it to me i am available .

**Comment by VaibhavArora314** [comment]
@MeetDOD make sure your changes do not overlap with #35 where heading will be added and a hero image

**Comment by MeetDOD** [comment]
@VaibhavArora314 sir i will keep that in mind.
