### ISSUE TITLE
[Feature Request]:  Newsletter Section Addition

### ISSUE THREAD

**Issue by Damini2004** [VaibhavArora314/StyleShare#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Newsletter section for latest update.

### Use Case

Subscribe for latest updates and all.

### Benefits

help to grab more user attention

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/119414762/0585bae0-f5f7-4265-a53a-08ddb344b185)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
this feature was also built initially by someone but since it didn't align with the website scope it was not added to website
