### ISSUE TITLE
[Feature Request]:  Floating Animation

### ISSUE THREAD

**Issue by Damini2004** [VaibhavArora314/StyleShare#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Floating animation for user engagement.

### Use Case

Floating animation for user engagement.

### Benefits

Floating animation for user engagement.

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/119414762/8fc675e6-3074-4a2a-bb77-234bf7a440a5)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
floating animation on what? please explain the issues in detail

**Comment by Damini2004** [comment]
@VaibhavArora314  the image will levitate on the x axis that will appear as eyecatchy experience.

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314  the image will levitate on the x axis that will appear as eyecatchy experience.

A tilt effect is currently being added to that image in other issue. So, I don't think this will look good with that.

**Comment by Damini2004** [comment]
@VaibhavArora314 as like home image it will levitate.

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 as like home image it will levitate.

check the website, tilt animation is added to the images
