### ISSUE TITLE
[Feature Request]: Implement google signup/sigin page

### ISSUE THREAD

**Issue by UtkarshBirla28** [VaibhavArora314/StyleShare#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement google signup/sigin page

### Use Case

Implement google signup/sigin page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
A google signin/signup issue already exists and is already being worked upon.

**Comment by UtkarshBirla28** [comment]
@VaibhavArora314 yes sorry i just saw that
