### ISSUE TITLE
[Feature Request]: Redirect to User Profile on Click of Profile Tab in Leaderboard

### ISSUE THREAD

**Issue by Saksham2k3s** [VaibhavArora314/StyleShare#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, clicking on the profile tab in the leaderboard does not redirect users to their profile page. To improve navigation and user experience, we need to ensure that clicking on a user's profile tab in the leaderboard redirects to their respective profile page.

![profile](https://github.com/VaibhavArora314/StyleShare/assets/129402285/020e3e0c-164b-4279-99dd-e7425f61d7de)

### Use Case

- Users can easily navigate to profile pages directly from the leaderboard, enhancing the overall usability of the platform.
- Making profiles more accessible encourages users to view and interact with other users' profiles, fostering a sense of community and engagement.

### Benefits

- Users can easily navigate to profile pages directly from the leaderboard, enhancing the overall usability of the platform.
- Making profiles more accessible encourages users to view and interact with other users' profiles, fostering a sense of community and engagement.

### Add ScreenShots

![profile](https://github.com/VaibhavArora314/StyleShare/assets/129402285/c0557c26-1fa7-457c-8c6d-c6eb2cab20d7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
clicking on the user's name redirects it to their profile so it is a simple copy-paste operation so lvl1

**Comment by MeetDOD** [comment]
@VaibhavArora314 assign this to me I will do this ASAP !
