### ISSUE TITLE
[Feature Request]: Add "Licensing Page" Reflecting "MIT Licence"

### ISSUE THREAD

**Issue by MastanSayyad** [VaibhavArora314/StyleShare#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @VaibhavArora314 

I would like to add Licensing Page reflecting MIT License to the website in footer section

![image](https://github.com/VaibhavArora314/StyleShare/assets/101971980/b58639e1-9f5f-45c3-96eb-926ce7457a07)

**Like this:**

![image](https://github.com/VaibhavArora314/StyleShare/assets/101971980/b5592ef6-0047-4d30-ace5-69461640ac11)

### Use Case

To improve professionalism and user clarity

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Since the MIT License is already present in repo, you can put repository LICENSE file link there
