### ISSUE TITLE
[Feature]: profile picture 

### ISSUE THREAD

**Issue by sivaprasath2004** [VaibhavArora314/StyleShare#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- In this project `/profile` page to add the user profile picture.
- Using for the firebase.
- This more User experience..

### Use Case

- please assign me..

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Instead of profile pictures, can we use profile avatars which are a set of predefined images our website will provide and the user can use it as their profile image?

**Comment by ayushvyasgit** [comment]
@sivaprasath2004  , i will implement add profile picture , in addition if their is no profile picture added ,then it will show 3d image avators . Assign me the task please

**Comment by MeetDOD** [comment]
@VaibhavArora314 assign me this I understood the approach and I will implement with below example :

![image](https://github.com/user-attachments/assets/d5e4b6c6-fed7-4917-9371-f49d0aa4b686)
