### ISSUE TITLE
[Feature Request]: Adding preloader to  the  website.

### ISSUE THREAD

**Issue by happyrao78** [VaibhavArora314/StyleShare#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Using the gsap  animation and react framer motion.

### Use Case

Will enhance the UI  of website.

### Add ScreenShots

https://github.com/VaibhavArora314/StyleShare/assets/138770813/a33d5540-887c-426a-8329-6c3ea1275c89

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
So, basically you want to a loading animation before the website loads up?

**Comment by happyrao78** [comment]
> So, basically you want to a loading animation before the website loads up?

Yes, thats only called a Pre-Loader.

**Comment by happyrao78** [comment]
@VaibhavArora314 Could you please assign the level label ?

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 Could you please assign the level label ?

I am not sure about the label, thinking around level 1 or 2 depending on the work which will be done. Will add the label after reviewing pull request.

**Comment by MeetDOD** [comment]
@VaibhavArora314 Assign this to me I will make this loader beautiful !
