### ISSUE TITLE
[Feature Request]: Adding name on every tab while navigating through pages / also adding favicon in admin panel

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In this issue i will create a document.title and it will show on the tab every page admin go on for example: if in manage posts page it will show style share | manage posts, at login style share | admin login like that in every page respectively.

Also, I am adding favicon on the admin panel.

### Use Case

UI

### Benefits

UX

### Add ScreenShots

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/a956ce12-db89-4ff9-bb97-03f2f1361847)

![image](https://github.com/VaibhavArora314/StyleShare/assets/120380073/d2b11da8-7050-4592-9627-f187abe39208)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
in admin the page title should be like Style Share Admin | Page name

**Comment by MeetDOD** [comment]
> in admin the page title should be like Style Share Admin | Page name

Noted 👍
