### ISSUE TITLE
[Feature Request]: Improve Contact Us Page

### ISSUE THREAD

**Issue by Prabhatyadav60** [VaibhavArora314/StyleShare#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

1. Improve Contact Us Page:
 Improving contact us page by adding a img  beside the form which changes at fixed interval to make page look impressive.
3. Add Favicon in Footer for "Our Contributors":
Include a favicon in the footer section specifically for "Our Contributors" to enhance the visual representation and user experience.

### Use Case

1. Improved Contact Us Page:
A larger, more appealing image will improve the user interface and user experience..
2. Favicon for "Our Contributors":
Adding a favicon will visually highlight the "Our Contributors".

### Benefits

Enhanced visual appeal and improved user experience on the "Contact Us" page.
Increased engagement from users due to the aesthetically pleasing design.

### Add ScreenShots

before contact us page--
![image](https://github.com/user-attachments/assets/18a3e8d5-b10b-439a-ac26-fad61c202429)

after---

https://github.com/user-attachments/assets/1ee6b3d4-81fc-4c5a-bff7-2537f894f3f2

footer with contributors favicon--
![image](https://github.com/user-attachments/assets/63cee84f-a107-4e35-a431-12e1d61c953e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
you can improve the Contact Us page and for the contributors' icon, it is already being implemented in another pull request.
