### ISSUE TITLE
[Feature Request] : ✨ Add a Page Scroll Progress Bar at the Top of Your Startup Webpage

### ISSUE THREAD

**Issue by TheNikhilRaj** [VaibhavArora314/StyleShare#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Explain feature request
Hey @jfmartinz ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no Page Scroll Progress Bar at the Top of Your Startup Webpage , which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Use Case

Explain your solution

![343870881-7f17e9d3-41c5-4fb0-a558-caf334552764](https://github.com/user-attachments/assets/e43ee8cb-549c-4694-b730-cce8b8132c00)

### Benefits

@VaibhavArora314 
Could you please assign me this issue under gssoc'24 ?

GSSOC'24

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
#139 but since no response from the assigned person go ahead.
