### ISSUE TITLE
[Feature Request]: Adding google authentication.

### ISSUE THREAD

**Issue by happyrao78** [VaibhavArora314/StyleShare#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Using  the firebase google auth, i want to add the google sign in feature.

### Use Case

Will enable the authenticity of the styleshare.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
#46
