### ISSUE TITLE
[Feature Request]: Fetching and creating separate page for comments for admin

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Like manage user, manage contact messages and manage posts, similarly I will create a page for comment so that admin can read and also delete the comment if the comments are spam, malicious or self-promotions etc...

### Use Case

Admin flexibility.

### Benefits

UI/UX

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Can we also add something like a button on every post on which when clicked the admin is redirected to this comment page but with a filter to show comments specific to that post

**Comment by MeetDOD** [comment]
> Can we also add something like a button on every post on which when clicked the admin is redirected to this comment page but with a filter to show comments specific to that post

Sorry, but I didn't got that can you elaborate the flow of your approach :)

**Comment by VaibhavArora314** [comment]
> > Can we also add something like a button on every post on which when clicked the admin is redirected to this comment page but with a filter to show comments specific to that post
> 
> Sorry, but I didn't got that can you elaborate the flow of your approach :)

So basically the comments will be having all the comments from all the posts. So I was thinking if it was possible to add some filter logic to filter comments for a particular post.

**Comment by MeetDOD** [comment]
like this way ?

Post 1:
 - c1
 - c2
 - c3
 
Post 2:
 - c1
 - c2
 - c3

and filtering all the comments ! for particular post ?

**Comment by MeetDOD** [comment]
like in the table there will be a post name and all the comments of it, 2nd post with all the comments and so on...
so that admin can do see and delete the comments according to the post.
?
I will show that in the table only but in different way !

**Comment by VaibhavArora314** [comment]
> like in the table there will be a post name and all the comments of it, 2nd post with all the comments and so on...
> so that admin can do see and delete the comments according to the post.
> ?
> I will show that in the table only but in different way !

Yes 👍
