### ISSUE TITLE
Navbar breaking into new line and white space

### ISSUE THREAD

**Issue by VaibhavArora314** [VaibhavArora314/StyleShare#462]
For some languages, the navbar breaks into the next line
![image](https://github.com/user-attachments/assets/23b4a8ad-b56a-4f5b-ba14-c5349ff61300)
![image](https://github.com/user-attachments/assets/c9a3d8d1-ee0b-405b-b1e1-adda2893a7f2)

Also on small devices, there is some white space below navbar
![image](https://github.com/user-attachments/assets/f02aa647-ade0-49b1-bb9f-17cb30f1e111)

**Comment by MeetDOD** [comment]
@VaibhavArora314 Assign me i will fix this issue 👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 I am changing the whole navbar, trust me it will look nice and like professional one 👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 what about we follow the previous approach we followed in the style share ?
![image](https://github.com/user-attachments/assets/55ee838a-c3f8-4b16-9966-abd17010fdf9)

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 what about we follow the previous approach we followed in the style share ?
> ![image](https://github.com/user-attachments/assets/55ee838a-c3f8-4b16-9966-abd17010fdf9)
> 

Go ahead just make sure it looks good and possibly better than the current one.

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 what about we follow the previous approach we followed in the style share ?
> > ![image](https://private-user-images.githubusercontent.com/120380073/350510110-55ee838a-c3f8-4b16-9966-abd17010fdf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTczMjcsIm5iZiI6MTcyMTQxNzAyNywicGF0aCI6Ii8xMjAzODAwNzMvMzUwNTEwMTEwLTU1ZWU4MzhhLWMzZjgtNGIxNi05OTY2LWFiZDE3MDEwZmRmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxOTIzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmNiZGU4MmQ2Zjc4NWYxNThjYjQ5MTFhZWZmOGI5ZTVmZDhjOWFmNTZjZThmMDQzZTUxNDE4Nzg2ZjkxYzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2HB3X2JZZf22tOB44f1a2M_UnYpXiMWqCC_J4IYducY)
> 
> Go ahead just make sure it looks good and possibly better than the current one.

Noted 🫡 !

**Comment by MeetDOD** [comment]
@VaibhavArora314 you can close this issue, to avoid many issues in style share :)
