### ISSUE TITLE
[Feature Request]: Implementing Non-copyable captcha 

### ISSUE THREAD

**Issue by anwesha2002** [VaibhavArora314/StyleShare#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

the captcha is copyable and the background is plain

### Use Case

The captcha should not be copyable and the background should not be clean that is the standard captcha

### Benefits

That will be the standardization of captcha and the project will be enhanced

### Add ScreenShots

![Screenshot 2024-07-20 165632](https://github.com/user-attachments/assets/15212377-4b70-4f48-a67f-4a973957c786)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@VaibhavArora314 assign this to me I will do this since I already did this issue that's why !

**Comment by VaibhavArora314** [comment]
@anwesha2002 any updates?
