### ISSUE TITLE
[Feature Request]: Styling the update profile form

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the form is not looking nice instead i will use the same pop up as used in the admin panel to read the contact us email sent by the users.

### Use Case

UI/UX

### Benefits

Profile section enhancement

### Add ScreenShots

Current:

![image](https://github.com/user-attachments/assets/89723849-0442-46c3-ad56-3c1ca180d050)

Approach:

![image](https://github.com/user-attachments/assets/c9994b3f-da94-47fa-a584-65370ee0d3b3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
sorry i don't get it, how will the 2nd one will be used as update form.

**Comment by MeetDOD** [comment]
> sorry i don't get it, how will the 2nd one will be used as update form.

Bruh 🗿

like this and more fields will be added by user social media linke after pr #474 

![image](https://github.com/user-attachments/assets/9044b43a-4538-45c6-9377-3fc3d4048efd)

It will look nice !
