### ISSUE TITLE
Improving footer UI

### ISSUE THREAD

**Issue by nagalakshmi08** [VaibhavArora314/StyleShare#48]
There is so much empty space in footer , so it looks incomplete.
![image](https://github.com/VaibhavArora314/StyleShare/assets/121669832/857c462e-f1e5-4c38-bdc1-82322d7e1940)
I would like to modify the content in footer , reduce the height , make links clickable and add some more social media icons in footer.

Please assign me this issue, i would like to contribute to this project under GSSoC'24.

**Comment by VaibhavArora314** [comment]
What will you add in the links as these pages are not developed yet

**Comment by VaibhavArora314** [comment]
hey, so in the company section, 
- the about us has to be linked with the about us section which will be added in #4
- create a dummy Contact Us page for now
- create a posts option that links to the posts page
- create a profile option if the user logged in
- remove careers and brand center option

in the legal pages section, link all the options to a dummy policy page for now

on the side of the GitHub icon, add an icon that links to the website

as for the empty spaces don't reduce them to much as it looks good and clean right now

**Comment by nagalakshmi08** [comment]
> hey, so in the company section,
> 
> * the about us has to be linked with the about us section which will be added in [Enhance Home page of the website #4](https://github.com/VaibhavArora314/StyleShare/issues/4)
 
> on the side of the GitHub icon, add an icon that links to the website


Okay sure, Thanks for assigning me this issue!
Just a small doubt here, should I add a top arrow icon which takes to the top of website?

**Comment by nagalakshmi08** [comment]
> on the side of the GitHub icon, add an icon that links to the website
> 
Hi, just a small doubt here. Should I add an icon that redirects to the homepage of this website, next to the GitHub icon?

**Comment by VaibhavArora314** [comment]
> > on the side of the GitHub icon, add an icon that links to the website
> 
> Hi, just a small doubt here. Should I add an icon that redirects to the homepage of this website, next to the GitHub icon?

yes
