### ISSUE TITLE
Design a Logo for the project StyleShare

### ISSUE THREAD

**Issue by MehtabAsHellic** [VaibhavArora314/StyleShare#49]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by VaibhavArora314** [comment]
Hey @MehtabAsHellic raise an issue (bug, feature, etc) you want to contribute to

**Comment by MehtabAsHellic** [comment]
> Hey @MehtabAsHellic raise an issue (bug, feature, etc) you want to contribute to

ok @VaibhavArora314

**Comment by VaibhavArora314** [comment]
Hey @MehtabAsHellic , a logo already exists being used as favicon, can you show some demo to compare them

**Comment by MehtabAsHellic** [comment]
> Hey @MehtabAsHellic , a logo already exists being used as favicon, can you show some demo to compare them

OK

**Comment by VaibhavArora314** [comment]
any updates @MehtabAsHellic?

**Comment by MehtabAsHellic** [comment]
> any updates @MehtabAsHellic?

give me a movement sharing some sample here @VaibhavArora314

**Comment by MehtabAsHellic** [comment]
as can you please assign and label this issue please @VaibhavArora314

**Comment by MehtabAsHellic** [comment]
![ss](https://github.com/VaibhavArora314/StyleShare/assets/101495398/9740c457-39d3-44d9-94f3-3f1b14c08e5e)


**@VaibhavArora314  so I use the background color of your current website and style and design the logo in such a way that it give the sense of tailwind CSS logo and understood the remark of The platform I hope you like it, please let me know your views.**

**Comment by VaibhavArora314** [comment]
> ![ss](https://private-user-images.githubusercontent.com/101495398/336136768-9740c457-39d3-44d9-94f3-3f1b14c08e5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTIzMTMsIm5iZiI6MTcxNzQ5MjAxMywicGF0aCI6Ii8xMDE0OTUzOTgvMzM2MTM2NzY4LTk3NDBjNDU3LTM5ZDMtNDRkOS05NGYzLTNmMWIxNGMwOGU1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwOTA2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTg0OGIzOThiMWM4OWNmZWE3ZjQyZTU2YWEzM2FiM2FjYjI2ZTE1Njc1MDBjY2FjZDU1ZGRkNmQwMTg3M2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x-pC2XQK34Yz7BjunjHpisvS_K_wJEjoyy5EpzSNo2g)
> 
> ![ss2](https://private-user-images.githubusercontent.com/101495398/336140219-a52da3b3-3a44-4af8-b2c9-926171c679a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTIzMTMsIm5iZiI6MTcxNzQ5MjAxMywicGF0aCI6Ii8xMDE0OTUzOTgvMzM2MTQwMjE5LWE1MmRhM2IzLTNhNDQtNGFmOC1iMmM5LTkyNjE3MWM2NzlhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwOTA2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTMxNmQzZDY3YjU3NDBiOTA1NzBlM2Q2ZjdhYmMyODA1NTc3OWE0OTBlZjk3NDZlNDRmYzhjNWIyNzllYTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s9dl4flxhQ_wogBXlllLAA8Fav35FMOCbMEUA3b68LU)
> 
> **@VaibhavArora314 so I use the background color of your current website and style and design the logo in such a way that it give the sense of tailwind CSS logo and understood the remark of The platform I hope you like it, please let me know your views.**

the current icon used as favicon looks more cleaner and better than this

**Comment by MehtabAsHellic** [comment]
> > ![ss](https://private-user-images.githubusercontent.com/101495398/336136768-9740c457-39d3-44d9-94f3-3f1b14c08e5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTIzMTMsIm5iZiI6MTcxNzQ5MjAxMywicGF0aCI6Ii8xMDE0OTUzOTgvMzM2MTM2NzY4LTk3NDBjNDU3LTM5ZDMtNDRkOS05NGYzLTNmMWIxNGMwOGU1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwOTA2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTg0OGIzOThiMWM4OWNmZWE3ZjQyZTU2YWEzM2FiM2FjYjI2ZTE1Njc1MDBjY2FjZDU1ZGRkNmQwMTg3M2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x-pC2XQK34Yz7BjunjHpisvS_K_wJEjoyy5EpzSNo2g)
> > ![ss2](https://private-user-images.githubusercontent.com/101495398/336140219-a52da3b3-3a44-4af8-b2c9-926171c679a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTIzMTMsIm5iZiI6MTcxNzQ5MjAxMywicGF0aCI6Ii8xMDE0OTUzOTgvMzM2MTQwMjE5LWE1MmRhM2IzLTNhNDQtNGFmOC1iMmM5LTkyNjE3MWM2NzlhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwOTA2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTMxNmQzZDY3YjU3NDBiOTA1NzBlM2Q2ZjdhYmMyODA1NTc3OWE0OTBlZjk3NDZlNDRmYzhjNWIyNzllYTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s9dl4flxhQ_wogBXlllLAA8Fav35FMOCbMEUA3b68LU)
> > **@VaibhavArora314 so I use the background color of your current website and style and design the logo in such a way that it give the sense of tailwind CSS logo and understood the remark of The platform I hope you like it, please let me know your views.**
> 
> the current icon used as favicon looks more cleaner and better than this

no problem @VaibhavArora314 , can just add this in the public folder maybe you used for future and make a pr please

**Comment by VaibhavArora314** [comment]
sure raise a pr for it @MehtabAsHellic , make sure the image size is not too large

**Comment by MehtabAsHellic** [comment]
> sure raise a pr for it @MehtabAsHellic , make sure the image size is not too large

thanks @VaibhavArora314 will add SVG file for the size it will perfect

**Comment by MehtabAsHellic** [comment]
please accept @VaibhavArora314 
https://github.com/VaibhavArora314/StyleShare/pull/121
