### ISSUE TITLE
[Feature Request]: Showing admin which user reacted to which post

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

With the help of this the admin will track the user activity and can understand the user more precisely.
So, the enhancement of the webapp will be there and component will be brought that it like by the users.

### Use Case

Understanding User behaviour

### Benefits

Tracking User activity

### Add ScreenShots

![image](https://github.com/user-attachments/assets/71efcb82-4bf8-49c6-9c10-18cc6370052c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
I don't think this is needed pretty much, we can simply show the count of likes on each posts and that is implemented

**Comment by MeetDOD** [comment]
> I don't think this is needed pretty much, we can simply show the count of likes on each posts and that is implemented

But if we do this remaining two features the dashboard will be completed in all the aspect and it will give admin whole webapp control and can handle the analytics part also !
That's why i raised this issue !

**Comment by VaibhavArora314** [comment]
Ok go ahead.
