### ISSUE TITLE
[Feature Request]: Want to make Testimonial Dynamic instead of static data

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to make that the user actually post the data in Testimonial via its profile but I am not sure about the approach @VaibhavArora314 can you guide me to make this feature.

In Testimonial the user name, avatar along with its review etc will be shown, Just tell me how to implement I will implement it ASAP. 

### Use Case

UI/UX

### Benefits

User Testimonial engagement

### Add ScreenShots

![image](https://github.com/user-attachments/assets/14462286-540b-4918-b99b-95054f242430)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
So instead of dummy profile photo and username, you want to show details of actual users and reviews from them?

**Comment by MeetDOD** [comment]
> So instead of dummy profile photo and username, you want to show details of actual users and reviews from them?

Ya like actual data from users what they taught about style share and all like most of the websites have !

**Comment by VaibhavArora314** [comment]
> > So instead of dummy profile photo and username, you want to show details of actual users and reviews from them?
> 
> Ya like actual data from users what they taught about style share and all like most of the websites have !

Ok so basically you can break this into two sub issues: one for allowing users to provide feedback and other for integrating that feedback to testimonials.

**Comment by MeetDOD** [comment]
@VaibhavArora314 I will start working on this ASAP because only 4 days is remaining !

**Comment by VaibhavArora314** [comment]
Also allow users to provide stars out of 5 with their feedback

**Comment by MeetDOD** [comment]
> Also allow users to provide stars out of 5 with their feedback

Ya, like their will be a form in which there is a stars and write your feedback likd that
