### ISSUE TITLE
[Bug]: set signin and signup buttons on the right side of the appbar thus enhancing ui

### ISSUE THREAD

**Issue by haseebzaki-07** [VaibhavArora314/StyleShare#516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The signup and signin buttons should be on the right part of the navbar /appbar rather than on the left part

### Expected behavior

The signup and signin buttons should be on the right part of the navbar /appbar rather than on the left part enhancing UI

### Add ScreenShots

![Screenshot 2024-07-27 165504](https://github.com/user-attachments/assets/d658c28d-d77d-4c38-9c16-d0bc6a759406)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
I think it looks good on the left side too, is there any particular reason to keep this on the right side?

**Comment by haseebzaki-07** [comment]
most of the websites has this functionality on the right side and any one visiting will first look for it on the right . It will improve the user experience.
