### ISSUE TITLE
[Bug]: Merging the sign in and signup button as a single button

### ISSUE THREAD

**Issue by lolpanda2004** [VaibhavArora314/StyleShare#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It is odd to have website have both buttons for sign in and sign up. furthermore, it can be on the right side to emphasize users attention towards it.

### Expected behavior

The merged button will lead to login and sign up

### Add ScreenShots

![better](https://github.com/user-attachments/assets/160a3381-0f7b-4e8a-be4b-320cf31a5ab4)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by lolpanda2004** [comment]
@VaibhavArora314 please do assign this issue to me

**Comment by VaibhavArora314** [comment]
For keeping it on right there exists another issue #512, you can merge this in one
