### ISSUE TITLE
[Feature Request]: Using Clerk Management Authentication

### ISSUE THREAD

**Issue by lolpanda2004** [VaibhavArora314/StyleShare#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

By using clerk authentication, its easier to create customized log in page and sign up page (including form validation) and other options to login in through google, github etc. Thus it will enhance like validation and easy for users to log in via other options rather than manually typing it out.

### Use Case

By using clerk authentication, its easier to create customized log in page and sign up page (including form validation) and other options to login in through google, github etc. I would consider this as an alternative to the already existing page.

### Benefits

It would be much more easier to save the data in the free trial version of it and secure the users data. Easier for the users to log in via multiple options as well. 

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Are there any secrets on the client side? As with the current deployment approach we cannot pass any secrets or env variables to the client side.

**Comment by lolpanda2004** [comment]
Yus there is but we can create an env example file that can go through the deployment the client would have to use their credentials (we can specify in comments or in documentation where to find the necessary credentials). So in their local computer, they can change the values in env.example file but then they need to create an env file and replace this with the content. At the end, they should remove the env file. Do note that documentation for this might be updated as well.

**Comment by VaibhavArora314** [comment]
If we add env variables in .env for deployment then we will have to commit it to GitHub which is not a solution I think.

**Comment by VaibhavArora314** [comment]
Is there any other way since we are serving build of react app via express server

**Comment by lolpanda2004** [comment]
As far as I know this is the only way to work with clerk through the .env file
