### ISSUE TITLE
 Improving and Adding new features on POST PAGE 

### ISSUE THREAD

**Issue by ISHITA1004** [VaibhavArora314/StyleShare#53]
1. Pagination: Add pagination or infinite scrolling to handle large numbers of posts, improving load times and user navigation.
2. User Interactions: Increase engagement by allowing users to like, comment, and share posts. Include counters for these interactions to show popularity.
3. Card Design: Improve the card design with subtle shadows and rounded corners to give a more modern and polished look.
4. Dark Mode Toggle: Provide a toggle switch to allow users to switch between dark and light modes, catering to different user preferences.
5. Profile Links: Allow usernames to be clickable, leading to user profiles where visitors can see more posts by the same author

**Comment by VaibhavArora314** [comment]
Hey @ISHITA1004 , a similar issue #40 already exists

**Comment by ISHITA1004** [comment]
If possible can I also contribute something in that.
Thank you

**Comment by VaibhavArora314** [comment]
hey @ISHITA1004, you can implement likes and comments functionality and also add profile links to respective author profiles as you stated before. rename this issue accordingly now.

As for the card design, you can raise a separate issue explaining with some demos or screenshots. 
And for dark mode toggle, it will be a big issue in itself so you can raise another issue for that later.

**Comment by ISHITA1004** [comment]
Got it, thanks!

**Comment by anshikatiwari20** [comment]
**Description:**
The task involves improving the existing POST PAGE and adding new features to enhance its functionality and user experience.

@VaibhavArora314 I am a GSSoC contributor and would like to work on improving and adding new features to the POST PAGE as described in issue #53. Could you please assign this issue to me? Thank you!

**Comment by VaibhavArora314** [comment]
> **Description:**
> The task involves improving the existing POST PAGE and adding new features to enhance its functionality and user experience.
> 
> @VaibhavArora314 I am a GSSoC contributor and would like to work on improving and adding new features to the POST PAGE as described in issue #53. Could you please assign this issue to me? Thank you!

All of these features have been implemented so I am closing this issue
