### ISSUE TITLE
[Bug]: Right side components of the navbar look distorted

### ISSUE THREAD

**Issue by haseebzaki-07** [VaibhavArora314/StyleShare#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Right side of the navbar having components like "new post" , "code editor" , "avatar" and "theme changing button" are not having proper spacing and are bit distorted  making UI ugly.

### Expected behavior

The components on the right side of navbar should have proper spacing enhancing UI.

### Add ScreenShots

![Screenshot 2024-07-30 205446](https://github.com/user-attachments/assets/a97989c7-b573-4b16-a6f3-d2c2e515181d)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Keep all the options on the right side. Also, increase the size of the profile icon it does not look good.

**Comment by haseebzaki-07** [comment]
okay noted!

**Comment by haseebzaki-07** [comment]
I am unable to set the backend on my machine because i am unable to generate the EMAIL_PASS from google

**Comment by VaibhavArora314** [comment]
> I am unable to set the backend on my machine because i am unable to generate the EMAIL_PASS from google, so i am unable to login/signup and am unable to fix the navbar issue

Remove or comment SEND_EMAIL environment variable from the .env file, it won't send email then and you will be able to signup/login. If the issue persists please tell me here.
