### ISSUE TITLE
➕ Feature: Add a Dedicated Licensing Page Reflecting the "MIT Licence"

### ISSUE THREAD

**Issue by aslams2020** [VaibhavArora314/StyleShare#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

hey @VaibhavArora314 @akbatra567 and @Ultimateutkarsh11 

To provide clear information about the licensing of the website's content and code, we need to add a dedicated "Licensing Page" that reflects the use of the MIT License.

**What will I do :**
1. **Create Licensing Page** 2. **Content for Licensing Page**
2.  Include a brief introduction explaining the importance of licensing.
     - Provide the full text of the MIT License.
3.  Will **Style the page to Follow the  theme of the website.**
4.  Will **Add "Licensing" in the Footer**, To **Navigate to this Separate Page** in Legal section.

for ex like this : 

![image](https://github.com/user-attachments/assets/fa9b7b9a-f8da-4313-bf15-198b6dc16a1b)

please assign me this issue under gssoc'24

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
There is no need to add a separate page for the MIT License since it is already present in GitHub repo. You can add a link to the License in repo in the footer and policy page.
