### ISSUE TITLE
Adding new features in POST Page like Search and Bookmark Option

### ISSUE THREAD

**Issue by ISHITA1004** [VaibhavArora314/StyleShare#54]
1. Search Functionality: Add a search bar to allow users to quickly find posts by keywords or tags.
2. Bookmarks or Favorites: Allow users to bookmark or favorite posts so they can easily access them later.

**Comment by VaibhavArora314** [comment]
for search functionality #38 exists, you can work on bookmarks if you want.

**Comment by ISHITA1004** [comment]
Yaa sure I will work on bookmark feature kindly assign this task to me .
Thank you

**Comment by ISHITA1004** [comment]
Got it, thanks!

**Comment by VaibhavArora314** [comment]
@MeetDOD assigning you this issue as you requested.

**Comment by MeetDOD** [comment]
@VaibhavArora314 i m always available for any contribution. Assign me this, i think i create a fresh issue for this because i want to change names and all ...

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 i m always available for any contribution. Assign me this, i think i create a fresh issue for this because i want to change names and all ...

Sure create a new issue, I will assign it to u
