### ISSUE TITLE
➕Feature: Adding Diagonal-Transitional Effect to "Each Contributors Card"

### ISSUE THREAD

**Issue by aslams2020** [VaibhavArora314/StyleShare#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @VaibhavArora314 , @akbatra567 

I want to suggest a new feature for "Contributors" Page.

I Want **to add a "Diagonal-Transitional" Effect Styling to each card** of the Contributors page. 
Which means On hovering on Every card, The card will display a Transitional Effect

**For ex.  Like this My prev Work-(I will follow the Style Share website theme)** 

https://github.com/user-attachments/assets/b70c3c22-fc3f-4397-854f-53a413bf4d60

**Current Contributor Cards -** 

https://github.com/user-attachments/assets/6dfe3f64-7f4c-43ff-95b5-d248007ae4c3

As you can see, currently the hovering effects are lagging and have no smooth hover effect.

Please Assign me this issue.

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Someone is working on it #540
You can do it after it is implemented.

**Comment by aslams2020** [comment]
@VaibhavArora314 Ohk

**Comment by VaibhavArora314** [comment]
@aslams2020 the other issue has been implemented, you can work on this now.
