### ISSUE TITLE
[Feature Request]: Showing user avatar in all tables in admin panel

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Sinec with the api also the user avatar is not appearing so i will fix this and fetch it in the admin panel

### Use Case

Admin engagement

### Benefits

Admin benefit

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b89c9946-fc08-41cb-9e62-ee4dfbaf708c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Also, in the frontend testimonials section if the user has not selected an avatar then the default avatar should be shown with user initials. Kindly look into this as well and make the changes in the same pr as well. 
![image](https://github.com/user-attachments/assets/334666b9-de1c-43ec-b0da-4b4f90c5e2c1)
