### ISSUE TITLE
Enhance Profile Page

### ISSUE THREAD

**Issue by VaibhavArora314** [VaibhavArora314/StyleShare#55]
Currently, there is no styling on the profile page. Add some styling so that the page looks better. Show proper handling of verification otp and generation/regeneration of otp.
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/ec575b7b-da88-4643-b575-d380fd880a48)

![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/fa6049f0-c81d-4d81-a08c-75e25f7a41d5)

![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/b06ef185-22a8-46fa-bbba-329db3f2ccbe)

**Comment by BHS-Harish** [comment]
Hey @VaibhavArora314 

I'm interested to working on the issue.

Please can you assign it to me..?
