### ISSUE TITLE
[Bug]: User Icon and Theme change option merging

### ISSUE THREAD

**Issue by Sourabh782** [VaibhavArora314/StyleShare#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we login into account the user Profile option and theme switching option gets compressed

### Expected behavior

there should be proper spacing between user profile option and theme switching option

### Add ScreenShots

![Screenshot 2024-08-01 194857](https://github.com/user-attachments/assets/fe166bdd-0601-4ac3-8e16-ae76d45f1c6c)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
Hey, this issue is assigned to issue #535

**Comment by Sourabh782** [comment]
> Hey, this issue is assigned to issue #535

Oh sorry, thanks for update
