### ISSUE TITLE
[Feature Request]: Adding download report button in every table for admin

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will use the same approach that i used for the dashboard download report button.
So that the admin can use the report everywhere

### Use Case

Admin engagement 

### Benefits

Admin enhancement 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@VaibhavArora314 I have to spilt this into 2 to 3 issues because all will have the route,controller and frontend integration, what you think?

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 I have to spilt this into 2 to 3 issues because all will have the route,controller and frontend integration, what you think?

Split this into 2 and don't split by frontend and backend work as then we won't be able to preview it. Split it into 2 parts in which the 1st part will have the download option for the first few options and in the 2nd part for the remaining.
