### ISSUE TITLE
[Bug]: Text not visible in light mode

### ISSUE THREAD

**Issue by zalabhavy** [VaibhavArora314/StyleShare#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/03084fb4-4de7-42f0-92ae-a9a473ea4677)

I will add text color black in light mode so it will be visible.

![image](https://github.com/user-attachments/assets/4e91a57d-f663-42e7-af48-41a80be74be3)

### Expected behavior

NA

### Add ScreenShots

NA

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by zalabhavy** [comment]
@VaibhavArora314 @akbatra567 @Ultimateutkarsh11 Please assign me this task !

Thank You !

**Comment by MeetDOD** [comment]
Already done and it is visible now refresh your browser !

![image](https://github.com/user-attachments/assets/8311d5ee-c997-4098-9d17-5ba9808c7492)

![image](https://github.com/user-attachments/assets/f465299c-10e8-4f5d-9502-a1cb5581d37f)

It's working fine

**Comment by VaibhavArora314** [comment]
already resolved.
