### ISSUE TITLE
[Feature Request]: Showing the stars in the testimonials given by the users

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently only the name, desc and avatar is showing in the testimonials.
I will also show the stars/rating given by the users.

### Use Case

UI/UX

### Benefits

More Information

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5c36f9c4-526f-49dc-a652-6e7b72a6501d)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MeetDOD** [comment]
@VaibhavArora314 How about this design ?

![image](https://github.com/user-attachments/assets/11530207-e90a-4201-8564-c700f359bcdc)

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 How about this design ?
> 
> ![image](https://github.com/user-attachments/assets/11530207-e90a-4201-8564-c700f359bcdc)
> 

Looks good, just some minor changes show stars above the user's name and make sure it's responsive
