### ISSUE TITLE
[Bug]: Showing the favourite status failed when style share is open in logout account

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you open in browser as a user without account this problem appears.
So, I will put the condition to solve this issue.

### Expected behavior

Backend problem

### Add ScreenShots

https://github.com/user-attachments/assets/332154f8-0a23-4957-b270-7df34aca4837

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
I am unable to reproduce this. Can you please specify some more details like did you add some posts favorite before logging out.

**Comment by MeetDOD** [comment]
> I am unable to reproduce this. Can you please specify some more details like did you add some posts favorite before logging out.

Copy the style share url and open it in the new account then their create accound in that new account mark some fav posts and then log out after that again reload the website you will see this issue !

**Comment by VaibhavArora314** [comment]
> > I am unable to reproduce this. Can you please specify some more details like did you add some posts favorite before logging out.
> 
> Copy the style share url and open it in the new account then their create accound in that new account mark some fav posts and then log out after that again reload the website you will see this issue !

I tried this but was still not able to reproduce it. Try clearing local storage and check again on your system.

**Comment by MeetDOD** [comment]
> > > I am unable to reproduce this. Can you please specify some more details like did you add some posts favorite before logging out.
> > 
> > 
> > Copy the style share url and open it in the new account then their create accound in that new account mark some fav posts and then log out after that again reload the website you will see this issue !
> 
> I tried this but was still not able to reproduce it. Try clearing local storage and check again on your system.

I tried on my friends laptop and in my college pc also, This error is showing up that's why I created the issue.
If it is fine then no problem.

Thank you.

**Comment by MeetDOD** [comment]
@VaibhavArora314 so I do this or no ?

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 so I do this or no ?

Go ahead.

**Comment by MeetDOD** [comment]
@VaibhavArora314 can you tell me where we used this api call ?

![image](https://github.com/user-attachments/assets/21bafc33-ab67-4af1-870e-253a4370a204)

**Comment by VaibhavArora314** [comment]
> @VaibhavArora314 can you tell me where we used this api call ?
> 
> ![image](https://private-user-images.githubusercontent.com/120380073/356264921-21bafc33-ab67-4af1-870e-253a4370a204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzA1ODUsIm5iZiI6MTcyMzEzMDI4NSwicGF0aCI6Ii8xMjAzODAwNzMvMzU2MjY0OTIxLTIxYmFmYzMzLWFiNjctNGFmMS04NzBlLTI1M2E0MzcwYTIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNTE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDBmZTBkMzY5MTZhMTgzZDZlOWMwZDdmYjg4MzVkNDBmZGZjZWZjYTViMjQ1MmJhNTNlNWIwMGVjMWFhOGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BhtT-3Yza4foI2Bca4SioDbbN1WqernjlD4dH-KkiOg)

Probably in post card component, check in the codebase

**Comment by MeetDOD** [comment]
> > @VaibhavArora314 can you tell me where we used this api call ?
> > ![image](https://private-user-images.githubusercontent.com/120380073/356264921-21bafc33-ab67-4af1-870e-253a4370a204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzA1ODUsIm5iZiI6MTcyMzEzMDI4NSwicGF0aCI6Ii8xMjAzODAwNzMvMzU2MjY0OTIxLTIxYmFmYzMzLWFiNjctNGFmMS04NzBlLTI1M2E0MzcwYTIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNTE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDBmZTBkMzY5MTZhMTgzZDZlOWMwZDdmYjg4MzVkNDBmZGZjZWZjYTViMjQ1MmJhNTNlNWIwMGVjMWFhOGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BhtT-3Yza4foI2Bca4SioDbbN1WqernjlD4dH-KkiOg)
> 
> Probably in post card component, check in the codebase

Bro I searched for 30 minute but i couldn't find it that's why I asked you :(

**Comment by MeetDOD** [comment]
@VaibhavArora314 I found that i was searching in post but it was in the postcard, my bad 😊
