### ISSUE TITLE
[Feature Request]: Add Dockerfile to the project

### ISSUE THREAD

**Issue by haseebzaki-07** [VaibhavArora314/StyleShare#572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding Dockerfile to the project integrated docker containerisation used for building and running local images of the project on one's machine that simplifies the application development and deployment process.

### Use Case

Docker can build images automatically by reading the instructions from a Dockerfile making local development and deployment of much ease.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
I thought this was supposed to be done in docker compose pull request as without dockerfiles of the backend, frontend and admin, we cannot build images and create containers.

**Comment by haseebzaki-07** [comment]
Yeah you are right i was exploring docker these days and got to know this recently I am fine with adding the Dockerfiles either here or to the earlier issue . Suggest me and I'll get going.

**Comment by VaibhavArora314** [comment]
> Yeah you are right i was exploring docker these days and got to know this recently I am fine with adding the Dockerfiles either here or to the earlier issue . Suggest me and I'll get going.

Add them to your other issue. If there is any issue, you can ping me.

**Comment by haseebzaki-07** [comment]
Sure
