### ISSUE TITLE
Add loading Skeleton instead of simple loading for cards in Posts page to look professional 

### ISSUE THREAD

**Issue by Utsavladia** [VaibhavArora314/StyleShare#577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/f6ca6691-66bc-4cb2-834b-01fa7a87c57c)

Something like this 
![image](https://github.com/user-attachments/assets/9b97472b-d4a1-4b96-83f9-de6e39983eef)

### Use Case

Add loading skeleton instead of simple loader

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Confused between level 1 and 2 for label. Will assign it after reviewing the work.

**Comment by Utsavladia** [comment]
@VaibhavArora314 okay added the skeletons kindly check it

> Confused between level 1 and 2 for label. Will assign it after reviewing the work.
