### ISSUE TITLE
[Feature Request]: Shoowing search suggesstion when typing on search bar

### ISSUE THREAD

**Issue by MeetDOD** [VaibhavArora314/StyleShare#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It will help user to browse fastly and efficiently.

### Use Case

UI/UX

### Benefits

Fast search

### Add ScreenShots

![image](https://github.com/user-attachments/assets/afc01b75-8155-4eb3-95e3-6eb8fc03ac80)

eg:

![image](https://github.com/user-attachments/assets/87d2e2f5-325b-42b0-8ab6-57625b6fcaa2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
How will you get these suggestions list?

**Comment by MeetDOD** [comment]
> How will you get these suggestions list?

from the card title i will map in the search bar dropdown !

**Comment by VaibhavArora314** [comment]
Since we are not fetching all the posts at the same time, maybe you can create an api to only get names of all the posts which can be further used for suggestions. Or an api to get the suggestions themselves but this may slow down the app due to repeated calls.
