### ISSUE TITLE
Code in code page should be viisble completely instead of overflow in small height

### ISSUE THREAD

**Issue by Utsavladia** [VaibhavArora314/StyleShare#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/5cc86fa4-540d-46a8-adec-b2dce8d6fb98)

### Use Case

This should take the complete height instead of auto in small window 
it will make the experience better 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
The code window did not full height because some code snippets are very long and users would have to scroll all the way down just to see the preview.

**Comment by Utsavladia** [comment]
@VaibhavArora314 
Understood.. though we can increaese the size of window somewhat to enahance the readability cuz currently it is frustrating to read the code in small window.. If you want 😌

**Comment by VaibhavArora314** [comment]
Increase the size of code window and modify code font size in smaller windows in this issue
