### ISSUE TITLE
[Bug]: Smaller the code text in mobile screeen to view properly

### ISSUE THREAD

**Issue by Utsavladia** [VaibhavArora314/StyleShare#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text of code should be smaller in mobile screen 

### Expected behavior

![image](https://github.com/user-attachments/assets/e5b8bc88-7635-429e-bb17-4b495ecf15f7)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Since this is a very few line change, do this with #589

**Comment by Utsavladia** [comment]
@VaibhavArora314 sure ✅
