### ISSUE TITLE
[Bug]: Search Dropdown Suggestions Overlapping with Filter Options

### ISSUE THREAD

**Issue by imashish22** [VaibhavArora314/StyleShare#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the search functionality on the "Posts" page, the dropdown suggestions for search terms overlap with the filter options, causing the UI to appear cluttered and making it difficult for users to select the correct suggestion.

**Steps to Reproduce:**

1. Navigate to the "Posts" page.
2. Begin typing a search query in the search bar.
3. Observe the dropdown suggestions that appear below the search bar.
4. Notice that the dropdown overlaps with the filter options, disrupting the UI.

### Expected behavior

The search suggestions dropdown should display cleanly without overlapping with the filter options. It should be positioned in a way that doesn't interfere with other UI elements.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/09e83215-155f-4e21-85c1-d61a3d3fdc7e)

**Possible Solutions:**

1. Adjust the z-index of the search suggestions dropdown to ensure it appears above or below other elements as needed.
2. Reposition the dropdown so that it does not overlap with the filter options.
3. Consider adding padding or margin to create clear separation between the dropdown and other UI components.

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
Sure go ahead @imashish22

**Comment by imashish22** [comment]
👍

**Comment by MeetDOD** [comment]
@VaibhavArora314 Assign it to me please I will ASAP 👍
