### ISSUE TITLE
Improve UI of  Sign In page

### ISSUE THREAD

**Issue by Ridhima10** [VaibhavArora314/StyleShare#63]
The UI of sign in page is not very appealing . i would like yo re-design it.
![Screenshot 2024-06-01 143346](https://github.com/VaibhavArora314/StyleShare/assets/85826117/9168108b-20f5-4668-bc73-8de260536052)

I will correct the alignment of buttons and add a heading and try to improve the overall UI as well as UX

Kindly assign me this issue.
Best regards

**Comment by VaibhavArora314** [comment]
hey the form is not loading properly on your machine
try clearing browser cache or use in different browser or incognito
![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/7e9080c4-1601-48d8-988a-ada67434dcef)
