### ISSUE TITLE
Improvement of sign up page

### ISSUE THREAD

**Issue by Ridhima10** [VaibhavArora314/StyleShare#64]
![Screenshot 2024-06-01 143619](https://github.com/VaibhavArora314/StyleShare/assets/85826117/8605dc6f-8bcf-4e83-b62e-184addd771e9)
The headings are very light in color and these is no title in the card.
I will also add a parallax effect to enhance the user interaction

**Comment by VaibhavArora314** [comment]
as stated in #63 , it is not loading properly on your machine
