### ISSUE TITLE
Feat: reCAPTCHA Implementation

### ISSUE THREAD

**Issue by antriksh-9** [VaibhavArora314/StyleShare#65]
Implementing reCAPTCHA v3 on the website will help in enhancing security, preventing spam and unauthorized access, protecting user data.
This also helps in preventing automated bots from accessing or submitting forms on the website.

Screenshot: 

![Screenshot 2024-05-18 113014](https://github.com/VaibhavArora314/StyleShare/assets/132576984/d49baf8c-1c4d-4edd-860e-52cd9b29faf6)

**Comment by antriksh-9** [comment]
Hey @VaibhavArora314 I want to work on this issue. 
Please assign it to me under GSSoC '24.

**Comment by VaibhavArora314** [comment]
can you provide more context of how this works

**Comment by antriksh-9** [comment]
> can you provide more context of how this works

The reCAPTCHA is integrated most likely to forms such as login form. 
First the reCAPTCHA will be loaded to website with unique site key, when the user reacts with the form it collects data and analyses it based on the score (0.5-1). A callback function is added to the submit/login button and when the form is submitted a post request is generated having secret key and reCAPTCHA token (contains info about interaction).
This tells whether the verification was done successfully or not.
