### ISSUE TITLE
Hero section Text Animation

### ISSUE THREAD

**Issue by Rohitha-pudu** [VaibhavArora314/StyleShare#68]
Adding text animation to the hero text

**Comment by VaibhavArora314** [comment]
can you provide some context about which text animation will be added to the hero text?

**Comment by Rohitha-pudu** [comment]
Text reveal animation /typewriter animation and for button moving border animation

**Comment by VaibhavArora314** [comment]
Can you provide some examples

**Comment by Rohitha-pudu** [comment]
https://typedjs.webflow.io/
https://portfolio-rohithapudu.vercel.app/
