### ISSUE TITLE
Add About Page

### ISSUE THREAD

**Issue by Hemashree21** [VaibhavArora314/StyleShare#7]
I want to design an About page to highlight the important features of the website. I have attached one of the templates below for reference.

![Screenshot 2024-05-13 180820](https://github.com/VaibhavArora314/StyleShare/assets/138188163/1c103aa5-65cb-46ae-94d8-97b8c7ad0b5d)

@VaibhavArora314 can you please assign this to me?

**Comment by VaibhavArora314** [comment]
There is no need to create a separate page for it, it can be covered in the home page

**Comment by akshaydubey430** [comment]
can u please assign me this so that i can design the about page
