### ISSUE TITLE
DESIGN CONTACT US PAGE

### ISSUE THREAD

**Issue by paulkrishanu4** [VaibhavArora314/StyleShare#73]
want to design contact us page and route the page to navbar keeping the responsive UI factor in mind.
Assign me to design it.

**Comment by VaibhavArora314** [comment]
will this be integrated with the backend also?

**Comment by paulkrishanu4** [comment]
yes fully functional contact page. infos will be stored in backend

**Comment by VaibhavArora314** [comment]
@paulkrishanu4 any updates?

**Comment by saurabhbakolia** [comment]
Hey, @VaibhavArora314 ,

If no-one is working on it, I would like to work on it. 
I also visited #129 

Thanks.

**Comment by VaibhavArora314** [comment]
@paulkrishanu4 since no response I am assuming you are not working on this

**Comment by saurabhbakolia** [comment]
![image](https://github.com/VaibhavArora314/StyleShare/assets/78996216/30bf218b-9a1d-4ea8-b622-34858801a89d)

I have created the Contact Us page as requested. Please provide feedback on the implementation.

**Comment by VaibhavArora314** [comment]
> ![image](https://private-user-images.githubusercontent.com/78996216/337941714-30bf218b-9a1d-4ea8-b622-34858801a89d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDU0NjEsIm5iZiI6MTcxNzk0NTE2MSwicGF0aCI6Ii83ODk5NjIxNi8zMzc5NDE3MTQtMzBiZjIxOGItOWExZC00ZWE4LWI2MjItMzQ4NTg4MDFhODlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE0NTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNjBiMjI2YzRhYzQ4MjliN2U3ZWMzNGY3ZDcxZGRkYmIxYWRiMWMwOGZiODAzMmY2YTc0YzQwMmJjNTg1NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._iqNMaNzE4kcELWuTJ0dQjS6u7LARl_cyx6m-eowsqw)
> 
> I have created the Contact Us page as requested. Please provide feedback on the implementation.

looks good, just make sure its integrated with backend and raise a pr after that

**Comment by saurabhbakolia** [comment]
I have made a pull request for this issue, Please check.
