### ISSUE TITLE
Dynamic code for year should be added at the bottom for footer

### ISSUE THREAD

**Issue by arpit4521** [VaibhavArora314/StyleShare#74]
![Screenshot 2024-06-02 040028](https://github.com/VaibhavArora314/StyleShare/assets/127679958/26324e17-b365-45e8-966d-c380e0bc0e4d)

here year should be added with dynamic nature

**Comment by arpit4521** [comment]
@VaibhavArora314 please assign me this issue under gssoc label and level

**Comment by VaibhavArora314** [comment]
it should look like `Copyright 2024-20xx StyleShare` but since the end year is currently the same as the start year so show `Copyright 2024 StyleShare`. This should be dynamically shown based on the year.
