### ISSUE TITLE
No syntax highlighting in the code snippet for code

### ISSUE THREAD

**Issue by Joyosmit** [VaibhavArora314/StyleShare#80]
There is no syntax highlighting present for the code snippet uploaded as a post.

Syntax highlighting will help users.

**Comment by VaibhavArora314** [comment]
@Joyosmit any updates?

**Comment by anshikatiwari20** [comment]
**Description:**
The task involves adding syntax highlighting to the code snippets in the project. Syntax highlighting improves the readability and understanding of code by using different colors and styles to distinguish various elements of the code.

@VaibhavArora314 I am a GSSoC contributor and would like to work on adding syntax highlighting to the code snippets as described in issue #80. Could you please assign this issue to me? Thank you!

**Comment by VaibhavArora314** [comment]
@Joyosmit any updates?

**Comment by Joyosmit** [comment]
Sry but I am unable to take out time for this. Pls assign some it to someone else

**Comment by VaibhavArora314** [comment]
@anshikatiwari20 any updates?

**Comment by MeetDOD** [comment]
@VaibhavArora314 I can do this, can you assign this to me if no one is working on it !
