### ISSUE TITLE
Bug: Footer Buttons are not clickable

### ISSUE THREAD

**Issue by ansh-h-mehta** [VaibhavArora314/StyleShare#88]
![image](https://github.com/VaibhavArora314/StyleShare/assets/99081110/b58221a9-1068-49a6-b9cd-158eb0707493)

When the user clicks on the footer buttons shown in the image, the user must be redirected to the respective pages. But this action is not being performed.

**Comment by ansh-h-mehta** [comment]
Please assign this issue to me under GSSOC'24. I'd be happy to fix it.

**Comment by VaibhavArora314** [comment]
this is the old footer and it has been updated now with all options being clickable.
