### ISSUE TITLE
No verification of user's email via OTP

### ISSUE THREAD

**Issue by Joyosmit** [VaibhavArora314/StyleShare#9]
When user signs up, there is no verification being done whether the email is their's or not. 
We need to send a OTP to the user for this.

https://github.com/VaibhavArora314/StyleShare/assets/143820879/86e5b634-5069-4819-884c-2116dfb3f4b8

Obviously, no such email as the one entered here exists as the one entered above.

**Comment by Joyosmit** [comment]
Pls assign me this issue

**Comment by VaibhavArora314** [comment]
How are you planning to send a verification link to the user?

**Comment by Joyosmit** [comment]
I will send an OTP using nodemailer.
