### ISSUE TITLE
[Feature Request]: Edit posts made by its owner

### ISSUE THREAD

**Issue by Parth18Shah** [VaibhavArora314/StyleShare#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature will allow the users to edit their posts and update them. If they own that post, an edit option will be provided to the user on the post details page.

### Use Case

This will allow more freedom and flexibility for the user to update their code to either improve their uploaded code snippet or correct any errors in it.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
hey @Parth18Shah, any updates?

**Comment by Parth18Shah** [comment]
Hey there, I'm just working on it. Apologies for the delay, I have been busy with other commitments for the past few days.
