### ISSUE TITLE
[Feature Request]: Add a contact us form

### ISSUE THREAD

**Issue by AkhilaSunesh** [VaibhavArora314/StyleShare#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 Add a contact us form
![image](https://github.com/VaibhavArora314/StyleShare/assets/140897461/adaa6553-bfd3-4854-b37c-a11090e119b7)
Kindly assign me this issue

### Use Case

More user friendly 

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
#73
