### ISSUE TITLE
[Feature Request]: Addition of JS scripts along with the HTML code for a particular component

### ISSUE THREAD

**Issue by Parth18Shah** [VaibhavArora314/StyleShare#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Allow users to add snippets of JS with their HTML code. This will include the following:
1) Updating the model to store the JS code on the database
2) Sanitizing this code to prevent harmful code and for security reasons 
3) Updating the UI

### Use Case

This will allow users to upload components like dropdowns and carousels, which usually require some form of JS to work. 

### Benefits

Allows the users to upload a broader range of components.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by VaibhavArora314** [comment]
hey @Parth18Shah, any updates?

**Comment by Parth18Shah** [comment]
There are no updates at the moment; just going through various approaches so I can implement this issue.
