### ISSUE TITLE
[Feature Request]: DESIGN ABOUT US PAGE

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As of now the about us page is empty.
i am interested to do it

### Use Case

 Building Trust and Credibility

### Benefits

Highlights core values, ethical standards, and commitment to quality or service.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
please assign me this task under GSSOC'24

**Comment by VaibhavArora314** [comment]
Another pr was opened for it and has been merged now so the about page is added to the project. #78
