### ISSUE TITLE
[BUG]: The image on the home page has watermarks in it 

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i wish to set a new image without any watermarks and it will definitely suite for ourwebsite

### Use Case

we have to be independent

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
please assign me this task under GSSOC'24

**Comment by VaibhavArora314** [comment]
can you specify which images has watermarks?

**Comment by manikumarreddyu** [comment]
it is changed after lastest update..
