### ISSUE TITLE
[Feature Request]: Adding favicon logo for the website

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding logo of website on the top left corner 

### Use Case

every website has their own logo..why not us !!

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
please assign me this task under GSSOC'24

**Comment by VaibhavArora314** [comment]
The favicon logo already exists

![image](https://github.com/VaibhavArora314/StyleShare/assets/84830429/c008fbd7-584d-4398-a69d-307576f189ac)
