### ISSUE TITLE
[Feature Request]: i want to improve UI of profile page

### ISSUE THREAD

**Issue by manikumarreddyu** [VaibhavArora314/StyleShare#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

our website profile page is looking dull..i wish to enhance the UI of profile page

### Use Case

It adds some beauty to our website

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by manikumarreddyu** [comment]
please assign me this task under GSSOC'24

**Comment by VaibhavArora314** [comment]
#55
